#!/usr/bin/env bash
#
# Generate the Homebrew formula for a built release, into dist/homebrew/: arm64 macOS, x64 and arm64 Linux.
#
# ⭐ HOMEBREW MAKES MAXON USABLE IN THE SHELL THAT INSTALLED IT. `brew install` links the binary into
# Homebrew's `bin` — `/opt/homebrew/bin` on macOS, `/home/linuxbrew/.linuxbrew/bin` on Linux — which is
# already on PATH, so there is no PATH edit and no new terminal. On macOS it also strips the quarantine
# attribute, so the Gatekeeper warning a downloaded archive earns does not appear.
#
# ⛔ THE BINARY IS LINKED INTO `bin` AS A SYMLINK, AND THAT IS SAFE — MEASURED, NOT ASSUMED. The
# compiler finds `stdlib/` by walking UP from its own executable, so a symlink whose directory has no
# `stdlib/` beside it would break every compile if the walk started at the LINK. It does not:
# `Process.executablePath()` resolves the link (`/proc/self/exe` on Linux), and a `maxon` reached through
# a symlink on PATH compiles against the stdlib in its real prefix. `homebrew.yml` tests exactly that on
# every platform before a formula is published.
#
# ⛔ THE TAP PREFIX IS REQUIRED, NOT A CONVENTION — `brew install maxon` INSTALLS SOMETHING ELSE.
# `maxon` in homebrew-cask is **Maxon App**, Maxon Computer's Cinema 4D / ZBrush installer, and a bare
# `brew install maxon` resolves to it. MEASURED: the attempt reported "Purging files for version
# 2026.5.0 of Cask maxon". So the fully-qualified `maxon-lang/tap/maxon` is the ONLY spelling that
# installs the language.
#
# ⚠ `brew tap` + a bare name is not a shortcut either: a third-party tap now needs `brew trust` before
# its formulae load, and the bare name would still hit the cask.
#
# ⚠ GENERATED, NOT COMMITTED: the formula carries the SHA256 of each archive, and a formula checked in
# beside the source is stale the moment a release is rebuilt.
#
# Usage:
#   installer/homebrew/generate.sh [<version>]
#
# Publish by committing the result to maxon-lang/homebrew-tap as Formula/maxon.rb.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$repo_root"

DIST="dist"
OUT="$DIST/homebrew"
REPO="maxon-lang/maxon"

# One archive per platform the formula serves. Intel Macs have no build, so the formula refuses them
# on macOS rather than naming a download that does not exist.
archive_for() {
	local found
	found="$(find "$DIST" -maxdepth 1 -type f -name "maxon-*-$1.tar.gz" | head -n1 || true)"
	[ -n "$found" ] || { echo "homebrew: no $1 archive in $DIST — download the release's archives first" >&2; exit 1; }
	echo "$found"
}

macos_archive="$(archive_for arm64-macos)"
linux_x64_archive="$(archive_for x64-linux)"
linux_arm_archive="$(archive_for arm64-linux)"

version="${1:-}"
if [ -z "$version" ]; then
	version="$(basename "$macos_archive" .tar.gz)"
	version="${version#maxon-}"
	version="${version%-arm64-macos}"
fi

url_of() { echo "https://github.com/$REPO/releases/download/v$version/$(basename "$1")"; }
sha_of() { sha256sum "$1" | cut -d' ' -f1; }

mkdir -p "$OUT"
formula="$OUT/maxon.rb"

{
	cat <<EOF
# Generated by installer/homebrew/generate.sh — do not edit by hand.
class Maxon < Formula
  desc "Systems language whose compiler is written in itself"
  homepage "https://maxon.dev"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "$(url_of "$macos_archive")"
      sha256 "$(sha_of "$macos_archive")"
    end
  end

  on_linux do
    on_intel do
      url "$(url_of "$linux_x64_archive")"
      sha256 "$(sha_of "$linux_x64_archive")"
    end
    on_arm do
      url "$(url_of "$linux_arm_archive")"
      sha256 "$(sha_of "$linux_arm_archive")"
    end
  end

EOF

	cat <<'EOF'
  def install
    # ⛔ THE COMPILER AND ITS STANDARD LIBRARY MUST STAY SIBLINGS. `maxon` finds `stdlib/` by walking up
    # from its own executable, so installing the binary into `bin` on its own would leave it with no
    # standard library at all. The whole tree goes into libexec, and `bin/maxon` is a symlink to it —
    # the compiler resolves that link, so the walk starts in the real prefix.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"maxon"
  end

  test do
    (testpath/"hello.maxon").write <<~MAXON
      typealias ExitCode = int(0 to 255)

      function main() returns ExitCode
      \tprint("hello\\n")
      \treturn 0
      end 'main'
    MAXON

    assert_match version.to_s, shell_output("#{bin}/maxon version")
    system bin/"maxon", "build", testpath/"hello.maxon", "-o", testpath/"hello"
    assert_equal "hello\n", shell_output(testpath/"hello")
  end
end
EOF
} > "$formula"

echo "homebrew: wrote $formula for $version"
echo "  arm64-macos: $(basename "$macos_archive")"
echo "  x64-linux:   $(basename "$linux_x64_archive")"
echo "  arm64-linux: $(basename "$linux_arm_archive")"
echo
echo "⚠ The release must be live before the formula resolves. To publish it:"
echo "    commit this file to maxon-lang/homebrew-tap as Formula/maxon.rb"
echo "  then it installs with:"
echo "    brew install maxon-lang/tap/maxon"
