#!/usr/bin/env bash
#
# Generate the Homebrew formula for a built release, into dist/homebrew/.
#
# ⭐ HOMEBREW IS WHAT MAKES MAXON IMMEDIATELY USABLE ON macOS. `brew install` links the binary into
# `/opt/homebrew/bin` (Apple silicon) or `/usr/local/bin` (Intel), both already on PATH — so `maxon`
# works in the shell that ran the install, with no PATH edit and no new terminal. Homebrew also strips
# the quarantine attribute, so the Gatekeeper warning a downloaded archive earns does not appear.
#
# ⛔ THE BINARY IS LINKED INTO `bin` AS A SYMLINK, AND THAT IS SAFE — MEASURED, NOT ASSUMED. The
# compiler finds `stdlib/` by walking UP from its own executable, so a symlink whose directory has no
# `stdlib/` beside it would break every compile if the walk started at the LINK. It does not:
# `Process.executablePath()` resolves the link, and a `maxon` reached through a symlink on PATH
# compiles correctly against the stdlib in its real prefix. Verified on macOS before this file existed.
#
# ⛔ THE TAP PREFIX IS REQUIRED, NOT A CONVENTION — `brew install maxon` INSTALLS SOMETHING ELSE.
# `maxon` in homebrew-cask is **Maxon App**, Maxon Computer's Cinema 4D / ZBrush installer, and a bare
# `brew install maxon` resolves to it. MEASURED: the attempt reported "Purging files for version
# 2026.5.0 of Cask maxon". This is the same trademark collision that forced `MaxonLang.Maxon` on winget,
# so the fully-qualified `maxon-lang/tap/maxon` is the ONLY spelling that installs the language.
#
# ⚠ `brew tap` + a bare name is not a shortcut either: a third-party tap now needs `brew trust` before
# its formulae load, and the bare name would still hit the cask.
#
# ⚠ GENERATED, NOT COMMITTED, for the winget manifest's reason: the formula carries the SHA256 of each
# archive, and a formula checked in beside the source is stale the moment a release is rebuilt.
#
# Usage:
#   installer/homebrew/generate.sh [<version>]
#
# Publish by committing the result to maxon-lang/homebrew-tap as Formula/maxon.rb.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$repo_root"

DIST="dist"
OUT="$DIST/homebrew"
REPO="maxon-lang/maxon"

arm_archive="$(find "$DIST" -maxdepth 1 -type f -name 'maxon-*-arm64-macos.tar.gz' | head -n1 || true)"
[ -n "$arm_archive" ] || { echo "homebrew: no arm64-macos archive in $DIST — run scripts/release.sh --package first" >&2; exit 1; }

base="$(basename "$arm_archive" .tar.gz)"
version="${1:-}"
if [ -z "$version" ]; then
	version="${base#maxon-}"
	version="${version%-arm64-macos}"
fi

arm_sha="$(sha256sum "$arm_archive" | cut -d' ' -f1)"

# ⚠ THE INTEL ARCHIVE IS OPTIONAL AND ITS ABSENCE IS STATED, NOT PAPERED OVER. There is no x64-macos
# target today, so the formula covers Apple silicon and says nothing about Intel rather than claiming a
# bottle that does not exist — a formula that fails to download is worse than one that declines to
# install.
x64_archive="$(find "$DIST" -maxdepth 1 -type f -name 'maxon-*-x64-macos.tar.gz' | head -n1 || true)"

mkdir -p "$OUT"
formula="$OUT/maxon.rb"

{
	cat <<EOF
# Generated by installer/homebrew/generate.sh — do not edit by hand.
class Maxon < Formula
  desc "Systems language whose compiler is written in itself"
  homepage "https://maxon.dev"
  version "$version"
  license any_of: ["MIT", "Apache-2.0"]

EOF

	if [ -n "$x64_archive" ]; then
		x64_sha="$(sha256sum "$x64_archive" | cut -d' ' -f1)"
		cat <<EOF
  on_macos do
    on_arm do
      url "https://github.com/$REPO/releases/download/v$version/$(basename "$arm_archive")"
      sha256 "$arm_sha"
    end
    on_intel do
      url "https://github.com/$REPO/releases/download/v$version/$(basename "$x64_archive")"
      sha256 "$x64_sha"
    end
  end

EOF
	else
		cat <<EOF
  # Apple silicon only: there is no x64-macos target yet.
  depends_on arch: :arm64
  url "https://github.com/$REPO/releases/download/v$version/$(basename "$arm_archive")"
  sha256 "$arm_sha"

EOF
	fi

	cat <<'EOF'
  def install
    # ⛔ THE COMPILER AND ITS STANDARD LIBRARY MUST STAY SIBLINGS. `maxon` finds `stdlib/` by walking up
    # from its own executable, so installing the binary into `bin` on its own would leave it with no
    # standard library at all. The whole tree goes into libexec, and `bin/maxon` is a symlink to it —
    # the compiler resolves that link, so the walk starts in the real prefix.
    libexec.install Dir["*"]
    bin.install_symlink libexec/"maxon"
  end

  test do
    (testpath/"hello.maxon").write <<~MAXON
      typealias ExitCode = int(0 to 255)

      function main() returns ExitCode
      \tprint("hello\\n")
      \treturn 0
      end 'main'
    MAXON

    assert_match version.to_s, shell_output("#{bin}/maxon version")
    system bin/"maxon", "build", testpath/"hello.maxon", "-o", testpath/"hello"
    assert_equal "hello\n", shell_output(testpath/"hello")
  end
end
EOF
} > "$formula"

echo "homebrew: wrote $formula for $version"
echo "  arm64-macos: $(basename "$arm_archive")"
echo "  sha256:      $arm_sha"
[ -n "$x64_archive" ] && echo "  x64-macos:   $(basename "$x64_archive")"
echo
echo "⚠ The release must be live before the formula resolves. To publish it:"
echo "    commit this file to maxon-lang/homebrew-tap as Formula/maxon.rb"
echo "  then it installs with:"
echo "    brew install maxon-lang/tap/maxon"
