#!/usr/bin/env bash
# The FILESYSTEM-CALL probe. Unlike every other generator here it writes a program to RUN, not a
# program to COMPILE: it measures what one `File.delete` / `File.exists` / `FilePath.changeExtension`
# COSTS, in nanoseconds and in allocations, so a per-compile cost paid in SYSCALLS can be priced.
#
# ⚠ BUILD IT WITH THE BOOTSTRAP (`./bin/maxon.exe build <out>`), NOT with shv2. That was written when
# shv2 could not compile `stdlib/File.maxon` at all; it now loads every stdlib module, so re-measure
# before assuming the restriction still binds. Either way it is not a weaker measurement: the shv2
# compiler BINARY is emitted by the bootstrap, from this same
# `stdlib/File.maxon` and this same emitted runtime, so a bootstrap-built program calling
# `File.delete` runs the identical machine code shv2's own `Compiler.discardPreviousOutput` runs.
#
# WHY IT EXISTS: `scale-test`'s memory columns cannot price a syscall. A `File.delete` allocates
# exactly ONE 40-byte record whatever it costs in time — and that record is not the path, it is the
# green-thread runtime's `SyncRequest`: `__io_submit_sync` (X86CodeEmitter.Runtime.cs) mm_raw_allocs
# one, enqueues it, SetEvents a SYNC WORKER THREAD and parks the caller until the worker completes
# it. So every `__ManagedFile` call is a cross-thread round trip, which is why one costs tens of
# MICROseconds on a box where the kernel call itself is a couple.
#
# Usage: genfsprobe.sh <iterations> <outfile>
#   iterations: how many times each primitive is repeated inside one timed loop (20000 is ~30 s).
#
# It prints one CSV line per case: case,iters,total_ns,ns_per_iter,allocs_per_iter,bytes_per_iter
# — the ns columns are wall (this is I/O, so thread-CPU time would measure the wrong thread), the
# alloc columns are exact.
set -euo pipefail
ITERS="$1"; OUT="$2"

cat > "$OUT" <<'MAXON_EOF'
// Generated by tests/ladders/genfsprobe.sh — see that script's header.
// BUILD WITH THE BOOTSTRAP: ./bin/maxon.exe build <this file>

typealias Count = int(0 to u64.max)
typealias ExitCode = int(0 to 255)

let Iterations = @ITERATIONS@ as Count
let IrFileExtension = ".ir"

function allocs() returns Count
	return __Builtins.mmAllocTotal() + __Builtins.mmRawAllocTotal()
end 'allocs'

function allocBytes() returns Count
	return __Builtins.mmAllocBytes() + __Builtins.mmRawAllocBytes()
end 'allocBytes'

// One failing File.delete: the path is not there. This is what a clean build sees, and what every
// spec test sees (the runner deletes each test's exe and .ir before the next one starts).
function deleteAbsent(p FilePath)
	try File.delete(p) otherwise ignore
end 'deleteAbsent'

// One File.exists on a path that is NOT there — `discardPreviousOutput`'s re-check, and the
// candidate GUARD for a conditional delete.
function existsAbsent(p FilePath)
	if File.exists(p) 'unexpected'
		panic("existsAbsent: the probe path exists")
	end 'unexpected'
end 'existsAbsent'

// One File.exists on a path that IS there — `requireOutputWritten`'s reading on the success path.
function existsPresent(p FilePath)
	if not File.exists(p) 'unexpected'
		panic("existsPresent: the probe path is missing")
	end 'unexpected'
end 'existsPresent'

// The CONDITIONAL form: exists-then-delete. If this is not cheaper than the bare failing delete,
// guarding the delete buys nothing on the common path and costs an extra syscall on the other one.
function guardedDeleteAbsent(p FilePath)
	if File.exists(p) 'present'
		try File.delete(p) otherwise ignore
	end 'present'
end 'guardedDeleteAbsent'

// The userland half of `discardPreviousOutput`: a byte scan and a String, no syscall at all.
function changeExtensionOf(p FilePath)
	let ir = p.changeExtension(IrFileExtension)
	if ir.isEmpty() 'unexpected'
		panic("changeExtensionOf: empty result")
	end 'unexpected'
end 'changeExtensionOf'

function writeOnly(p FilePath, payload ByteArray)
	try File.writeBinary(p, content: payload) otherwise panic("writeOnly: write failed")
end 'writeOnly'

function deleteThenWrite(p FilePath, payload ByteArray)
	try File.delete(p) otherwise panic("deleteThenWrite: delete failed")
	try File.writeBinary(p, content: payload) otherwise panic("deleteThenWrite: write failed")
end 'deleteThenWrite'

// The composite `Compiler.discardPreviousOutput` + `Compiler.requireOutputWritten` add to a compile
// whose output is absent: ONE changeExtension, two failing deletes, two exists (one closing the
// discard, one opening the write check).
function discardAndRequire(p FilePath)
	deleteAbsent(p.changeExtension(IrFileExtension))
	deleteAbsent(p)
	existsAbsent(p)
	existsAbsent(p)
end 'discardAndRequire'

// How `Compiler.resolveOutputPath` builds the output path: INTERPOLATE the platform extension onto
// the raw `-o` value, then hand the result to FilePath. The interpolation is load-bearing — see the
// note in `main`.
function resolveLike(override String) returns FilePath
	return try FilePath.from("{override}.exe") otherwise panic("resolveLike: bad path")
end 'resolveLike'

// The dispatcher exists so every case is timed by ONE loop, whose own cost is therefore identical
// across cases and cancels out of any comparison between them.
function runCase(which Count, absent FilePath, present FilePath, forwardSpelt FilePath, payload ByteArray)
	if which == 0 'changeExt'
		changeExtensionOf(absent)
	end 'changeExt' else if which == 1 'delAbsent'
		deleteAbsent(absent)
	end 'delAbsent' else if which == 2 'exAbsent'
		existsAbsent(absent)
	end 'exAbsent' else if which == 3 'guarded'
		guardedDeleteAbsent(absent)
	end 'guarded' else if which == 4 'exPresent'
		existsPresent(present)
	end 'exPresent' else if which == 5 'writeOnly'
		writeOnly(present, payload: payload)
	end 'writeOnly' else if which == 6 'delWrite'
		deleteThenWrite(present, payload: payload)
	end 'delWrite' else if which == 7 'composite'
		discardAndRequire(absent)
	end 'composite' else if which == 8 'changeExtFwd'
		changeExtensionOf(forwardSpelt)
	end 'changeExtFwd' else 'unknown'
		panic("runCase: no case {which}")
	end 'unknown'
end 'runCase'

function measure(name String, which Count, absent FilePath, present FilePath, forwardSpelt FilePath, payload ByteArray)
	// One untimed pass so no first-call lazy allocation and no cold directory entry is billed.
	runCase(which, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)

	let a0 = allocs()
	let b0 = allocBytes()
	let start = Clock.nowNanos()
	var i = 0 as Count
	while i < Iterations 'loop'
		runCase(which, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)
		i = i + 1
	end 'loop'
	let total = Clock.elapsedNanos(start)
	let da = allocs() - a0
	let db = allocBytes() - b0

	print("{name},{Iterations},{total},{total / Iterations},{da / Iterations},{db / Iterations}")
end 'measure'

function main() returns ExitCode
	// ⭐ THE TWO SPELLINGS. `absent` and `forwardSpelt` end up as the SAME PATH TEXT and cost
	// DIFFERENT amounts in `changeExtension`, and the reason is not the separator — it is what the
	// stored String is a PRODUCT OF. Both are built the way `resolveOutputPath` builds one, by
	// INTERPOLATION. On Windows `FilePath.create` then normalizes `/` to `\` through
	// `String.replace`, so the forward-spelt one is handed on as a replace() result while the
	// native-spelt one is handed on as the interpolation's own buffer — and `changeExtension` is
	// two allocations cheaper on the former. Build both from LITERALS instead and the difference
	// vanishes, which is how you can tell it is the buffer and not the bytes.
	//
	// This is why a per-compile figure read off `scale-test` (whose runner spells its paths with
	// `FilePath.join`, i.e. `\`) is 2 allocations larger than one taken by driving the same compile
	// by hand with `/` arguments.
	let absent = resolveLike("temp\\fsprobe-absent")
	let forwardSpelt = resolveLike("temp/fsprobe-absent")
	let present = try FilePath.from("temp\\fsprobe-present.bin") otherwise panic("bad path")

	// The comparison IS the experiment's control: unless the two spellings normalize to the same
	// text, a difference between their changeExtension costs would just be a difference of path.
	if absent.toString() != forwardSpelt.toString() 'notSameText'
		panic("the two spellings did not normalize to the same path, so the two changeExtension rows below are not comparable and this host's FilePath does not normalize separators")
	end 'notSameText'

	var payload = ByteArray.create()
	var b = 0 as Count
	while b < 64 'fill'
		payload.push(65)
		b = b + 1
	end 'fill'
	try File.writeBinary(present, content: payload) otherwise panic("could not create the present probe")
	try File.delete(absent) otherwise ignore

	print("case,iters,total_ns,ns_per_iter,allocs_per_iter,bytes_per_iter")
	measure("change_extension", which: 0, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)
	measure("change_extension_forward_spelt", which: 8, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)
	measure("delete_absent", which: 1, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)
	measure("exists_absent", which: 2, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)
	measure("guarded_delete_absent", which: 3, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)
	measure("exists_present", which: 4, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)
	measure("write_only", which: 5, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)
	measure("delete_plus_write", which: 6, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)
	measure("discard_plus_require", which: 7, absent: absent, present: present, forwardSpelt: forwardSpelt, payload: payload)

	try File.delete(present) otherwise ignore
	return 0
end 'main'
MAXON_EOF

sed -i "s/@ITERATIONS@/$ITERS/" "$OUT"
