// <auto-generated/>
// GENERATED FROM docs/error-codes.txt. DO NOT EDIT.
//
// Add or change a code in that file, then run `maxon error-codes generate`.
// `maxon error-codes check` (run by every build that consumes this file) fails if it drifts.

namespace MaxonSharp.Compiler;

/// <summary>
/// Structured error codes for the compiler, grouped by compilation stage:
/// 1xxx lexer, 2xxx parser, 3xxx semantic, 4xxx IR, 5xxx code emitter,
/// 6xxx PE writer, 9xxx internal.
/// </summary>
public enum ErrorCode {
  /// <summary>
  /// A string literal reached end-of-line or end-of-file with no closing quote.
  /// </summary>
  LexerUnterminatedString = 1002,
  /// <summary>
  /// A backslash escape in a string or character literal names no known escape.
  /// </summary>
  LexerInvalidEscape = 1004,
  /// <summary>
  /// A literal brace appears unescaped in a string literal. A '{' opens interpolation, so write '\{' to embed a literal brace.
  /// </summary>
  LexerUnescapedBrace = 1006,
  /// <summary>
  /// A block comment reached end-of-file with no closing delimiter.
  /// </summary>
  LexerUnterminatedBlockComment = 1007,

  /// <summary>
  /// The parser met a token that cannot appear at this point in the grammar.
  /// </summary>
  ParserUnexpectedToken = 2001,
  /// <summary>
  /// A type was required here and the token stream had something else.
  /// shv2 emits it for the two shapes where a name IS present but is not a
  /// usable type: a bare sized type as a typealias RHS (`typealias I = i64`),
  /// and an `as` cast target that names a typealias the reading file cannot
  /// see. A cast target no declaration binds ANYWHERE is E3011 instead, which
  /// is sharper than the reference's blanket E2003 -- see
  /// specs-shv2/cast-target-type-resolution.md.
  /// It also covers the shape where NO name is present and none can be
  /// inferred: a closure parameter past the first in a container `map`'s
  /// transform (`nums.map(function(a, b) gives a + b)`). That position types
  /// ONE parameter, by the arity the transform is declared at, so a later
  /// untyped one has nothing to take a type from -- see
  /// specs-shv2/closure-param-type-inference.md. An untyped parameter in a
  /// position that offers nothing at all is E2015 instead, which names the one
  /// construct that does infer.
  /// </summary>
  ParserExpectedType = 2003,
  /// <summary>
  /// An expression is not well formed, or is well formed and not usable where only a constant is. Broader than its C#/v1 name (ParserExpectedExpression) suggests: all three compilers report five distinct message families under it -- a primary was required and the token stream had something else; a name in an expression has no binding in scope; a binary arithmetic/shift operator got a non-numeric operand; a unary '-' got a non-numeric operand; and a top-level binding's initializer does not fold to a compile-time constant.
  /// </summary>
  ParserExpectedExpression = 2004,
  /// <summary>
  /// The parser reached end-of-file with a construct still open.
  /// </summary>
  ParserUnexpectedEof = 2007,
  /// <summary>
  /// A block's 'end' label does not match the label its header opened.
  /// </summary>
  ParserMismatchedEndLabel = 2008,
  /// <summary>
  /// A specific token was required here. Reports as: Expected 'X' but got 'Y'.
  /// </summary>
  ParserExpectedToken = 2010,
  /// <summary>
  /// An integer literal does not fit the range of its type.
  /// </summary>
  ParserLiteralOverflow = 2011,
  /// <summary>
  /// A declaration cycle: something is defined in terms of itself. Broader than 'import cycle', which is one of several shapes all three compilers report under it -- others are a cycle among top-level constants ('let A = B + 1' / 'let B = A + 1'), where no initializer can be evaluated because each waits on the other, and a circular typealias ('typealias A = Array with A', or a mutual pair), which describes an infinite type with no finite layout. The list is not a roster to keep exhaustive: what the code means is the cycle, not the construct it was found in.
  /// </summary>
  ParserCircularDependency = 2012,
  /// <summary>
  /// An assignment targets a binding declared 'let'. Declare it 'var', or do not reassign it.
  /// </summary>
  ParserImmutableVariable = 2013,
  /// <summary>
  /// A match arm falls through to the next arm while the enclosing function still owes a return.
  /// </summary>
  ParserMatchFallthroughWithReturn = 2025,
  /// <summary>
  /// A match does not cover every case of its scrutinee and has no default arm.
  /// </summary>
  ParserMatchNotExhaustive = 2026,
  /// <summary>
  /// Two match arms test the same pattern; the second can never run.
  /// </summary>
  ParserMatchDuplicatePattern = 2027,
  /// <summary>
  /// A match's arms, or a ternary's two branches, produce different types (or a ternary condition is not bool).
  /// a match arm or postfix-ternary's two arms produce different types,
  /// or a ternary condition is not bool. Mirrors the C# bootstrap's
  /// ParserMatchTypeMismatch -- thrown at parse time so it wins over the
  /// body-finish unused-variable check (E3012).
  /// </summary>
  ParserMatchTypeMismatch = 2028,
  /// <summary>
  /// A match's 'default' arm is not the last arm.
  /// </summary>
  ParserMatchDefaultNotLast = 2029,
  /// <summary>
  /// A match arm opens a block but gives it no block label.
  /// </summary>
  ParserMatchMissingBlockId = 2042,
  /// <summary>
  /// A match arm's block label does not match the label its arm opened.
  /// </summary>
  ParserMatchMismatchedBlockId = 2043,
  /// <summary>
  /// A top-level constant's initializer is not a compile-time constant.
  /// </summary>
  ParserNonConstantInitializer = 2045,
  /// <summary>
  /// A match over an enum may only carry a 'default' arm if that arm throws.
  /// </summary>
  ParserMatchDefaultEnumMustThrow = 2046,
  /// <summary>
  /// 'break'/'continue' carries the label of the innermost enclosing loop. The label is redundant.
  /// `break 'lab'` / `continue 'lab'` where `lab` names the
  /// innermost enclosing loop (with no intervening match for `break`). The
  /// label is redundant -- unlabeled `break`/`continue` already targets
  /// that loop. Emitted from `resolveBreakTarget` / `resolveContinueTarget`.
  /// </summary>
  ParserRedundantLoopLabel = 2048,
  /// <summary>
  /// A match arm's body is a block-opening statement. Each arm body must be a single statement.
  /// Phase 9 Stage 0: a match arm body cannot be a block-opening
  /// statement (`if` / `while` / `for` / `match` / block-form `try`).
  /// Each arm body is a single statement; block-form constructs would
  /// allocate persistent slots that leak on every error path through
  /// the match.
  /// </summary>
  ParserMatchBlockStatement = 2049,
  /// <summary>
  /// An 'otherwise' block form declares no error binding.
  /// TWO messages on one code, and the bootstrap emits both: a block-form
  /// `try 'l' ... end 'l'` with NO `otherwise` handler at all, and one whose
  /// handler declares no `(e)`. The author's mistake is one thing -- an
  /// incomplete handler -- told apart only by how far they got.
  /// </summary>
  ParserOtherwiseBlockMissingBinding = 2050,
  /// <summary>
  /// A declaration uses a name reserved by the compiler.
  /// </summary>
  ParserReservedIdentifier = 2051,
  /// <summary>
  /// A call labels its first argument. The first argument is positional; only the second and later arguments take 'name:' labels.
  /// a call site labeled its first argument (`f(name: value, ...)`).
  /// The first argument is positional-only; only the second and subsequent
  /// arguments may be labeled.
  /// </summary>
  ParserFirstArgCannotBeNamed = 2052,
  /// <summary>
  /// A shift ('shl'/'shr') whose count the compiler FOLDED and found NEGATIVE --
  /// 'a shl -1', 'a shl -(1)', 'let SHIFT = -1' ... 'a shl SHIFT'. A negative count is
  /// not a shift the other way: the hardware MASKS it, so 'a shl -1' silently computed
  /// 'a shl 63' -- the MAXIMUM LEFT shift, a wrong answer with the opposite sign.
  /// Maxon follows Go: the count must be non-negative; a constant one is this compile
  /// error, and one that only appears at RUN TIME panics.
  /// WARNING -- a count of 64 OR MORE IS NOT THIS ERROR. It is a legal, well-defined
  /// shift that moves every bit out ('x shl 64' == 0), because Go puts no upper limit
  /// on a shift count. This code briefly rejected it, which OVER-rejects a correct
  /// program. The compiler SATURATES such a count instead of masking it.
  /// A PARSE-time check, positioned at the count as WRITTEN. It asks the CONSTANT
  /// FOLDER, not the token shape: 'let SHIFT = -1' is the same -1 as the literal, and a
  /// check that only looked for a bare literal token missed its own motivating example.
  /// </summary>
  ParserShiftCountNegative = 2054,
  /// <summary>
  /// A `test` declaration appears in a file whose name does not end in `.test.maxon`. Tests are
  /// confined to those files by ONE rule checked in ONE place, so which declarations a build
  /// carries is answerable from the file list alone -- no flag, no attribute, nothing to read the
  /// body for. The message names the fix: rename the file, or move the declaration.
  /// </summary>
  ParserTestOutsideTestFile = 2058,
  /// <summary>
  /// A `test` declaration's name is the empty character literal (`test ''`). The name is the
  /// test's whole identity -- it is what the reporter prints and what `end ''` must match -- and
  /// an empty one names nothing. Refused at the declaration rather than at the report, where an
  /// unnamed failure would be the least useful place to discover it.
  /// </summary>
  ParserTestEmptyName = 2059,
  /// <summary>
  /// '__line__' or '__file__' appeared somewhere other than a function parameter's default
  /// value -- in an ordinary expression, or as a struct FIELD default, which is a different
  /// thing despite the shared '= &lt;expr&gt;' spelling.
  /// These two are a CALLING CONVENTION, not a reflection facility: each expands at the CALL
  /// SITE, and a parameter default is the only position that has a call site to expand
  /// against. A field default expands at a struct literal and an ordinary expression expands
  /// nowhere, so neither has an answer to give.
  /// Raised at TWO grammar positions, from one rule: the expression position catches it when
  /// the token is evaluated, and the field-default position catches it when the tokens are
  /// CAPTURED. The capture-side check is not merely a better error location -- without it a
  /// field default nobody triggers is never expanded, and the misuse would go undiagnosed.
  /// </summary>
  ParserCallerLocationOutsideDefault = 2060,
  /// <summary>
  /// A numeric literal's text is not a number -- two decimal points ('1.5.3'), or any byte the
  /// number grammar does not admit.
  /// IT REPLACES A PANIC, and the panic's premise is why this code exists. The parser used to
  /// assert a malformed literal was UNREACHABLE from source, on the ground that Lexer.scanNumber
  /// only ever hands over digits, '_', '.', 'e'/'E' and an exponent sign -- so a rejection could
  /// only mean the lexer and the number reader had diverged, a compiler defect rather than a
  /// program's. That premise was FALSE: the lexer's trailing-byte rule appended a SECOND '.' to a
  /// token that already carried a fraction, so '1.5.3' reached the reader as '1.5.' and CRASHED
  /// the compiler. A parser must be able to answer 'that literal is not well-formed' with a
  /// position, and a layer that cannot say no is a layer whose caller's leniency has nowhere to
  /// surface.
  /// </summary>
  ParserMalformedNumericLiteral = 2068,
  /// <summary>
  /// A '__Builtins.ucd*' load names a compiler-owned Unicode table its intrinsic does not read.
  /// Each intrinsic reads exactly ONE table, because the label and the STRIDE are one fact:
  /// 'ucdByteAt' reads '__ucd_bmp', one byte per BMP codepoint, and 'ucdI64At' reads
  /// '__ucd_supp', an array of 8-byte packed range entries. Reading either with the other's
  /// stride cannot produce an answer -- only a wrong one -- so the pairing is refused rather
  /// than assumed, and the message names the table the intrinsic DOES read.
  /// ⚠ IT IS A SECURITY GUARD AND NOT A TYPO CHECK, which is why it is a refusal at the label
  /// token rather than a link failure later. Both reference compilers turned the label into a
  /// FILE NAME under the stdlib directory, so an unchecked one was a PATH TRAVERSAL: MEASURED,
  /// the bootstrap answered '__Builtins.ucdByteAt("__ucd_../../../evil", 0)' by reaching for
  /// 'stdlib/helpers/string/ucd_../../../evil.bin' and reporting the miss as E9001 with a C#
  /// stack trace. v1 guards only the '__ucd_' PREFIX (LowerMaxonToStd.maxon:8464-8486), which
  /// does not close it: '__ucd_../../x' carries the prefix and still escapes. A ROSTER of the
  /// tables the compiler actually owns is what closes it, and it is the same roster in both
  /// compilers.
  /// NOT E2010: a label that is not a string LITERAL at all is refused at the token by the
  /// ordinary 'expected a string literal' rule, because that is a shape the parser can state
  /// without knowing which intrinsic it is reading for.
  /// </summary>
  ParserUcdTableLabelUnknown = 2070,
  /// <summary>
  /// 'countof(T)' was asked of a type with no element count. A count is a coordinate of the
  /// INSTANCE, which the 'with N Type' form writes -- 'Vector with 3 Int' states 3, and so does
  /// any other generic instantiated that way. A ranged alias has no elements at all, and a
  /// growable 'Array' keeps its length in the record rather than in its type, so neither has an
  /// answer to give; 'arr.count()' is the runtime question.
  /// IT ARRIVES FROM TWO STAGES, because the bootstrap decides the operand's instance in two
  /// places. An operand that names a type outright is settled by the parser. 'Self', or the
  /// enclosing declaration's own name, names an instance the parser does not yet know -- the
  /// same body is compiled once per instantiation -- so it DEFERS, and monomorphization reports
  /// it against the copy it was compiling, naming the instance. That is why an ordinary generic
  /// written 'Box with 3 Int' answers where 'Box with Int' is refused: the declaration is not
  /// what is being asked.
  /// Answering 0 is not available: it is a sentinel no reader could tell from a real count.
  /// maxon-shv2 refuses the same programs through its E2015 unsupported-construct catch-all,
  /// and refuses more of them -- it does not monomorphize, so it can only ask whether the
  /// enclosing declaration is the sized container it knows by name. specs/countof.md states
  /// which shapes the two compilers part company on, and why.
  /// </summary>
  CountofTypeStatesNoElementCount = 2071,
  /// <summary>
  /// 'countof(Self)' was written inside a closure. A closure body is lifted to its own
  /// top-level function, and that function is emitted ONCE rather than compiled per generic
  /// instance -- so the enclosing method's instance, which is the whole source of the answer,
  /// is not in scope there however the method itself was instantiated.
  /// NOT E2071, which is about a type that HAS no count: here the type has one and the
  /// position cannot reach it. The cure differs accordingly -- read 'countof(Self)' into a
  /// binding outside the closure and capture the integer.
  /// It is refused at the parse because the alternative is measured: the twin expression
  /// 'sizeof' has no such gate, and 'sizeof(Element)' inside a closure in a generic body
  /// reaches lowering with its operand unsubstituted and aborts as E9001 with a C# stack
  /// trace and no source position at all.
  /// </summary>
  CountofSelfInLiftedClosure = 2072,

  /// <summary>
  /// The program declares no 'main' function.
  /// </summary>
  SemanticNoMain = 3001,
  /// <summary>
  /// 'main' declares a return type other than ExitCode.
  /// </summary>
  SemanticMainWrongReturnType = 3002,
  /// <summary>
  /// A name used in an expression has no binding in scope.
  /// </summary>
  SemanticUndefinedVariable = 3003,
  /// <summary>
  /// A call names a function that does not exist -- a typo, or a callee not visible from here.
  /// </summary>
  SemanticUndefinedFunction = 3004,
  /// <summary>
  /// A value's type does not match the type required at this position.
  /// </summary>
  SemanticTypeMismatch = 3005,
  /// <summary>
  /// A name is declared twice where exactly one binding is legal: two functions with the same signature, a top-level `let`/`var` declared twice in a file, a TYPE name claimed by two declarations, or a local shadowing a 'self' field.
  /// a duplicate definition or a local-vs-self-field shadow. Two
  /// shapes share the code: (a) two function definitions with the same
  /// name and signature -- fires from `reportDuplicateFunction` in the
  /// parser for same-file duplicates and from the project-level main
  /// registration for cross-file `main` collisions; (b) a local
  /// declaration inside an instance method whose name collides with a
  /// `self.field` (matches the C# bootstrap's broader interpretation of
  /// "duplicate definition" -- the local would silently shadow the field);
  /// (c) two top-level `let`/`var` declarations of one name in a file --
  /// fires from `isRedeclaredBinding` at the real parse in shv2 and from a
  /// per-file declared-name set in the bootstrap's CollectAndEvaluateTopLevelDecls;
  /// a `let` and a `var` share one storage key, so kind is irrelevant. The
  /// top-level twin of (a); (d) a TYPE name claimed by two declarations --
  /// `type` / `enum` / `union` / `interface` / `typealias` all file one name
  /// in one whole-program namespace, and a fixed resolution cascade used to
  /// pick the winner silently. Fires from `commitTypeNameDecls` in shv2 at the
  /// merge. Kind-independent exactly as (c) is: what is refused is the SECOND
  /// declaration of the name, whichever keyword introduced either of them --
  /// UNLESS THE TWO DECLARATIONS CANNOT SEE EACH OTHER, which is the whole
  /// rule (`typeNamePairMayCoexist` in shv2). Three ways that holds: two
  /// `typealias` declarations in different files, whatever their FORMS (each
  /// alias form is scoped, and an ambiguity between two an author could both
  /// name is E3063 at the reference rather than a refusal of the
  /// declarations); a nominal declaration against a FILE-PRIVATE alias in
  /// another file; and a pair drawn from two LAYERS -- a `stdlib/`
  /// declaration and a user one are never both in scope. What still collides
  /// is one FILE declaring a name twice, two NOMINAL declarations, and a
  /// nominal declaration against an alias that is exported or `module`-visible
  /// from another file in the same layer. A pair of typealiases that does
  /// collide is E3061 rather than this code; (e) a name claimed
  /// twice in the COMPILED type namespace -- a generic instantiation has no
  /// source name, so the compiler joins its base to its arguments (`Box with
  /// String` -&gt; `Box_String`) and derives every per-type symbol from that
  /// string, which a declared `type Box_String` derives its own from too.
  /// Fires from `checkTypeSymbolNamespace` in shv2, whole-program, after the
  /// instantiations are interned. Two INSTANTIATIONS can claim one compiled
  /// name as well, `_` being a legal name character and the join therefore
  /// not injective. A `typealias` is not a claimant here: it mints no symbol
  /// of its own.
  /// </summary>
  SemanticDuplicateDefinition = 3006,
  /// <summary>
  /// A call cannot pick a unique overload: two or more candidates match it indistinguishably.
  /// call site cannot pick a unique overload because multiple
  /// variants have indistinguishable signatures at this call. Emitted when
  /// two overloads share the same parameter types and the caller doesn't
  /// disambiguate with named arguments. Matches the C# bootstrap wording.
  /// </summary>
  SemanticAmbiguousFunctionCall = 3007,
  /// <summary>
  /// A symbol is referenced from another file but is not declared 'export'.
  /// </summary>
  SemanticSymbolNotExported = 3008,
  /// <summary>
  /// A conversion that cannot be proven safe: an explicit cast whose source range does
  /// not fit the destination (`256 as Byte`), an explicit cast that is lossy or
  /// meaningless (`5.0 as int`, `true as int`), or the SAME lossy conversion reached
  /// IMPLICITLY, where a value meets a declared type it cannot reach without loss
  /// (`takeInt(3.7)`, `return 3.7` from a `returns int`). One code, because it is one
  /// fact: the answer to every one of them is an explicit `trunc`/`round`/`floor`/`ceil`.
  /// The implicit half was a WRONG ANSWER until P1.0d.4 -- specs/type-casting.md
  /// rejected `5.0 as int` while specs/implicit-type-conversion.md silently truncated
  /// the identical conversion at a call argument.
  /// </summary>
  SemanticUnsafeCast = 3009,
  /// <summary>
  /// A cast is redundant: the destination type already admits every value the source type can hold.
  /// </summary>
  SemanticUnneededCast = 3010,
  /// <summary>
  /// A named type resolves to no declared type -- a typo, or a type this compiler slice does not have.
  /// </summary>
  SemanticUnknownType = 3011,
  /// <summary>
  /// A local binding is declared and never read.
  /// </summary>
  SemanticUnusedVariable = 3012,
  /// <summary>
  /// A value-returning function can reach its end without returning, or a 'return' in it carries no value.
  /// </summary>
  SemanticMissingReturn = 3013,
  /// <summary>
  /// A field not declared 'export' is read or written from outside its own type.
  /// The gate is the TYPE, not the FILE, and it covers WRITES as well as reads --
  /// both measured against the bootstrap: `type B` touching `type A`'s unexported
  /// field is E3014 in the same file, and `v.private = 42` reports it exactly as
  /// `return v.private` does. This line said "read from another file" until P1.1a
  /// wave 3 and was wrong on both counts. Neither compiler's CHECK ever agreed
  /// with it -- v1 gates on `structName == enclosingType`
  /// (TypeResolution.maxon:8204) -- so it was the prose that drifted, and it
  /// drifted in one place and was read in three: this entry is the only copy, and
  /// correcting it corrects every generated registry at once.
  /// Initialization is exempt: every field, exported or not, may be named in a
  /// struct literal, because the type itself determines what fields exist and
  /// visibility only governs access AFTER construction (specs/export-var-fields.md).
  /// (was internally `semanticTypeResolutionCycle` while the
  /// unexported-field-access check was unimplemented). Bootstrap parity
  /// reclaims 3014 for the field-visibility diagnostic; the typealias-cycle
  /// diagnostic moves to 3091 (a code unused on both sides).
  /// </summary>
  SemanticUnexportedFieldAccess = 3014,
  /// <summary>
  /// A type claims to implement an interface but does not define all of its members.
  /// </summary>
  SemanticPartialInterfaceImpl = 3016,
  /// <summary>
  /// A generic argument violates the 'where' constraint declared on the type parameter.
  /// </summary>
  SemanticWhereConstraintViolation = 3017,
  /// <summary>
  /// A field access names a field the type does not have.
  /// </summary>
  SemanticUnknownField = 3018,
  /// <summary>
  /// An immutable ('let') binding is passed to a parameter the callee mutates, or a mutating method is called on it.
  /// a mutating method (push/pop/set/append/...) or a parameter-mutating
  /// function is called on an immutable (`let`-bound) receiver/argument. The
  /// receiver's data would be modified through a binding the user declared
  /// immutable. Emitted by the Maxon-tier borrow/mutation check.
  /// </summary>
  SemanticImmutableRefToMutatingParam = 3019,
  /// <summary>
  /// An enum declares the same case name twice.
  /// </summary>
  SemanticEnumDuplicateCase = 3030,
  /// <summary>
  /// Two enum cases declare the same raw value.
  /// </summary>
  SemanticEnumDuplicateRawValue = 3031,
  /// <summary>
  /// An enum case's raw value has a type other than the enum's declared raw-value type.
  /// </summary>
  SemanticEnumRawValueTypeMismatch = 3032,
  /// <summary>
  /// A match arm names a case the scrutinee's enum does not have.
  /// </summary>
  SemanticEnumUnknownCase = 3034,
  /// <summary>
  /// A match arm's payload-binding pattern supplies the wrong number of bindings for the case's payload.
  /// a match-arm payload-binding pattern (`case(x, y)`) supplies
  /// the wrong number of bindings for the case's declared payload. Emitted
  /// by `parseCaseBindingPattern` when an arity check can be performed at
  /// parse time, or deferred to TypeResolution when the case's owning
  /// union isn't yet known.
  /// </summary>
  SemanticEnumWrongBindingCount = 3035,
  /// <summary>
  /// A call passes a different number of arguments than the callee declares parameters.
  /// </summary>
  SemanticWrongArgCount = 3036,
  /// <summary>
  /// 'main' is declared 'throws'. There is no caller left to handle the error.
  /// </summary>
  SemanticMainCannotThrow = 3054,
  /// <summary>
  /// 'try' is applied to a call that cannot throw.
  /// </summary>
  SemanticTryRequiresThrowingFunction = 3055,
  /// <summary>
  /// A throwing call is made without 'try'.
  /// </summary>
  SemanticThrowingFunctionRequiresTry = 3057,
  /// <summary>
  /// 'otherwise' is written without a 'try'.
  /// </summary>
  SemanticOtherwiseRequiresTry = 3058,
  /// <summary>
  /// An 'otherwise' handler's value has a type other than the 'try' expression's type.
  /// It carries a SECOND message on the same fault seen from the value side: a `try` in a VALUE
  /// POSITION over a callee that returns nothing -- `'f' does not return a value`, anchored on the
  /// `try`. A BINDING is a value position too, so `if let x = try voidF()` (and `if let _ =`, which
  /// discards a result that does not exist) is refused here as well. That arm was missing until
  /// E3124's rung added it: the condition form shares the try-call REWRITE with the expression form
  /// but had never shared the question about the rewrite's RESULT, so the bootstrap declared no
  /// binding and blamed the USE (`E2004: Undefined variable`) while shv2 panicked in
  /// `maxonTypeOfTag`. NOT E3124, which is the opposite mismatch -- a value produced and dropped.
  /// </summary>
  SemanticErrorTypeMismatch = 3059,
  /// <summary>
  /// Two typealiases in scope declare the same name.
  /// Two `typealias` declarations of one name in DIFFERENT files are legal,
  /// whatever their forms: every alias form is scoped, a non-exported one is
  /// file-local (specs/duplicate-typealias.md), and an ambiguity between two
  /// an author could both name is a property of the USE -- E3063 at the
  /// reference -- rather than a refusal of the declarations. What this code
  /// refuses is ONE FILE declaring the name twice, which no qualification
  /// could disambiguate. shv2 raises it from `commitTypeNameDecls` when BOTH
  /// declarations are typealiases; a colliding pair involving a
  /// `type`/`enum`/`union`/`interface` is E3006 instead.
  /// </summary>
  SemanticDuplicateTypeAlias = 3061,
  /// <summary>
  /// A typealias is declared and never used.
  /// "Used" means the NAME appears in a type position in its OWN declaring
  /// file. An exported alias is exempt (one file cannot see another's uses),
  /// and being implicitly inferable from a bare `[...]` literal is not a use.
  /// </summary>
  SemanticUnusedTypeAlias = 3062,
  /// <summary>
  /// a bare-name type reference has more than one reachable
  /// typealias definition under directory-as-module rules. The user must
  /// write the directory-qualified form (`dir.Name`) to disambiguate.
  /// Mirrors E3095 (functions) but operates on the typealias registry.
  /// </summary>
  SemanticAmbiguousTypeAlias = 3063,
  /// <summary>
  /// a pure-function call's result was discarded. Pure callees must
  /// have their result used -- neither bare `foo()` nor `_ = foo()` is
  /// permitted. Fires from `checkDiscardedResults`.
  /// shv2 raises it at TWO doors. A tuple assignment whose every target is `_`
  /// (`(_, _) = makePair(10, b: 32)`, `specs/tuple-assign.md`) uses none of the result,
  /// and the whole-program effect summary judges the callee. A discarded MATH INTRINSIC
  /// (`round(10)` as a statement) needs no summary: the roster is machine instructions, so
  /// the statement is provably dead. Its bare-call and `_ =` doors over DECLARED callees
  /// stay shelved in `specs-shv2/discarded-results.md`.
  /// </summary>
  SemanticDiscardedPureResult = 3064,
  /// <summary>
  /// an impure-function call's result was discarded without the
  /// explicit `_ =` opt-in. The impure-call result still has to flow into
  /// either a binding (`let r = foo()`) or an explicit discard
  /// (`_ = foo()`). Fires from `checkDiscardedResults`.
  /// </summary>
  SemanticDiscardedImpureResult = 3065,
  /// <summary>
  /// A 'union' value is compared with '=='/'!='. Unions carry no synthesized equality; use 'match'.
  /// a `union` value was compared with `==` / `!=`. Unions carry no
  /// synthesized equality -- a new case can't be added without every match site
  /// being forced to handle it, so the only way to inspect a union is `match`.
  /// Enums (which auto-implement Equatable) are unaffected. Stdlib source is
  /// exempt (trusted). Emitted from `maybeRewriteCmpToEquals` in TypeResolution;
  /// mirrors the C# bootstrap's `SemanticEnumNotComparable`.
  /// </summary>
  SemanticEnumNotComparable = 3066,
  /// <summary>
  /// a textual self-assignment (`x = x`, `p.x = p.x`) or a
  /// discard-assignment whose RHS isn't a function call (`_ = 42`). The
  /// former has no effect; the latter is the historic shape for opting out
  /// of a "discarded result" warning, but a non-call RHS makes the discard
  /// nonsensical. csharp and selfhosted raise it from `parseVarAssignment`,
  /// `parseLocalFieldAssignment`, and `parseDiscardAssignment`.
  /// shv2 raises both shapes from the one door `Parser.rejectDegenerateAssignment`,
  /// and its rule is textual for BOTH halves: it refuses a place chain assigned
  /// to itself token for token, and a discard whose RHS is a bare LITERAL.
  /// That makes it LOOSER than csharp in two places and STRICTER in two others,
  /// and the strict direction is the one that can refuse a program csharp accepts:
  /// LOOSER -- shv2 admits `x = (x)` (parenthesized: different tokens) and
  /// `_ = someBinding` (the discard-a-binding idiom the corpus uses to satisfy
  /// E3012), both of which csharp's semantic rule refuses. "LITERAL" also
  /// excludes `_ = true` / `_ = false`, which shv2 lexes as KEYWORDS rather than
  /// literal kinds; no program in the tree writes either, and a second literal
  /// list spelled out for two token kinds would duplicate the one list
  /// (`tokenIsLiteralKind`) that `tokenCanBeAName` already shares.
  /// STRICTER -- shv2 refuses `self.n = self.n` and `a.b.c = a.b.c`, which csharp
  /// compiles clean (its `IsFieldSelfAssignment` matches one field name behind a
  /// struct var-ref, so it sees neither a `self` receiver nor a multi-hop chain).
  /// shv2 also decides BEFORE name resolution and the mutability check, so an
  /// immutable or undeclared target reports this code where csharp reports
  /// "cannot assign to immutable variable" or undefined-variable -- a difference
  /// of precedence between two true complaints, not of what is legal.
  /// </summary>
  SemanticSelfAssignment = 3067,
  /// <summary>
  /// The 'is'/'is not' reference-identity operator is applied to a primitive, which has no object identity.
  /// the `is` / `is not` reference-identity operator was applied to a
  /// primitive value (`int`, `float`, `bool`, `byte`, ...). Identity only has
  /// meaning for reference types (structs are heap pointers); primitives are
  /// values with no object identity. Emitted from the `is`-operand type check
  /// in TypeResolution. Mirrors the C# bootstrap's
  /// `SemanticRefIdentityOnPrimitive`.
  /// shv2 raises it in the PARSER (`Parser.emitReferenceIdentity`), where the
  /// operand tags are already known -- the same tier it states every other
  /// operand rule at -- rather than in a later type pass. It refuses a wider
  /// operand set than the word "primitive" alone suggests, and the reasons
  /// are not all the same reason. An enum case and an opaque type parameter
  /// are VALUES with no object anywhere. A `union` box and a function value
  /// genuinely ARE one-word addresses, and are refused because no spec on
  /// any of the three compilers pins an identity reading for them and both
  /// references refuse them by the same "is the operand a struct value?"
  /// test -- so admitting either would be shv2 inventing a semantics, not
  /// porting one. An existential is a FAT pointer, so a one-word compare
  /// would silently ignore its witness half. Widening the admitted set
  /// yields a POINTER COMPARE, never a type error, so a tag added without a
  /// reading is a wrong answer rather than a missing one. See
  /// `TypeRules.tagHasReferenceIdentity`.
  /// </summary>
  SemanticRefIdentityOnPrimitive = 3068,
  /// <summary>
  /// '=='/'!=' is applied to a type that does not implement Equatable.
  /// </summary>
  SemanticEqRequiresEquatable = 3069,
  /// <summary>
  /// borrow conflict -- a collection was mutated (e.g. `arr.push(x)`)
  /// while a reference into its backing buffer is still live (e.g.
  /// `let s = try arr.get(0) ...`). A growth could reallocate the buffer
  /// and dangle the outstanding reference. Emitted by the Maxon-tier
  /// `runMaxonBorrowCheck` pass. Mirrors the C# bootstrap's
  /// `SemanticBorrowConflict` (same code, same message format).
  /// </summary>
  SemanticBorrowConflict = 3070,
  /// <summary>
  /// a statement appears in the same straight-line block body
  /// immediately after a `return`, `throw`, `panic(...)`, `break` or
  /// `continue`. The trailing statement is unreachable -- control never falls
  /// through a block-terminating statement -- so it is dead code. Emitted by
  /// the parser's statement-list loop when a terminator is not the last
  /// statement of its block. Control-flow that creates separate blocks
  /// (a `return` inside an `if`, with code after the `if`) does NOT trigger
  /// this: that following code is reachable on the else path. Mirrors the C#
  /// bootstrap's `SemanticUnreachableCode` (same code, same message format).
  /// In shv2 it is a CORRECTNESS rule and not only a lint: a block's
  /// terminator lives in a slot `setTerminator` overwrites, so an accepted
  /// statement that terminates the block itself (an `if`, `while`, `for`,
  /// `match`) silently REPLACES the `return`/`break` already there. The
  /// deprecated v1 compiler applies the rule to `return`/`throw`/`panic`
  /// only; shv2 follows the bootstrap and covers `break`/`continue` too,
  /// which `specs/break.md` pins.
  /// </summary>
  SemanticUnreachableCode = 3071,
  /// <summary>
  /// a struct-literal names a compiler builtin managed type
  /// (`__ManagedFile`, `__ManagedMemory`, `__ManagedDirectory`, ...). These
  /// carry an opaque runtime handle and must be obtained through their static
  /// factory methods (e.g. `__ManagedFile.openRead`), never built directly.
  /// Emitted by the parser at the struct-literal site. Mirrors the C#
  /// bootstrap's `SemanticBuiltinTypeConstruction`.
  /// </summary>
  SemanticBuiltinTypeConstruction = 3072,
  /// <summary>
  /// an `async f()` call targets a function that never yields (contains
  /// no await / I/O stub call, transitively). `async` is only for I/O-concurrent
  /// work -- a non-yielding callee would run to completion synchronously on the
  /// spawning thread, so the spawn is pointless. Emitted by `checkAsyncYielding`.
  /// Mirrors the C# bootstrap's `AsyncNonYielding`.
  /// </summary>
  AsyncNonYielding = 3073,
  /// <summary>
  /// A match arm names a case in qualified form (`Color.red`). The scrutinee's enum
  /// is already known at the arm, so the bare case name suffices.
  /// </summary>
  SemanticMatchQualifiedCaseName = 3075,
  /// <summary>
  /// a struct literal (`Type{...}`) is written outside the type's own
  /// methods. Construction is restricted to the type's own methods / static
  /// factories so invariants can be enforced at the single construction point;
  /// external callers must go through a `static function create(...)`. Exempt:
  /// `Self{...}` and `Type{...}` inside `Type`'s own body, plus construction
  /// through a typealias visible at the site (inner alias of the current
  /// type/extension, or a top-level alias). Emitted by `parseStructLiteral`.
  /// Mirrors the C# bootstrap's `SemanticConstructorRestriction`.
  /// </summary>
  SemanticConstructorRestriction = 3076,
  /// <summary>
  /// a local declared with `var` is never reassigned, so it should
  /// be a `let`. Detected after type resolution by
  /// `checkVarShouldBeLetForEntry` (a `var` whose name never appears in the
  /// per-function reassigned-var set). E3012 (unused variable) takes
  /// precedence -- an unused `var` reports as unused, not as should-be-let.
  /// Mirrors the C# bootstrap's `SemanticVarShouldBeLet`.
  /// shv2 decides it at the declaring function's `end` (`reportVarShouldBeLet`)
  /// off the same candidate list E3012 walks, reading a per-function name set
  /// (`mutabilityExercisedNames`) that seven doors record into, and REPORTS it
  /// past the backend so a body with any other diagnostic never also reports
  /// this one. shv2 additionally counts a MOVE-OUT as a use of mutability,
  /// which neither reference does: there `var` and `let` copy alike, while in
  /// shv2 the keyword decides move-vs-alias, so advising `let` would silently
  /// turn a move into an alias.
  /// </summary>
  SemanticVarShouldBeLet = 3077,
  /// <summary>
  /// `var b = a` (or `var b = a.field`) where the source `a` is an
  /// immutable (`let`) binding of a reference type (struct / enum /
  /// function). Copying an immutable reference-type binding into a mutable
  /// one would alias the same heap value through a writable name; the user
  /// must either keep `b` immutable (`let`) or take an independent copy via
  /// `clone()`. Value-typed sources (int/float/bool/byte) are independent
  /// copies and are allowed. Detected after type resolution by
  /// `checkVarFromImmutableForEntry`. Mirrors the C# bootstrap's
  /// `SemanticVarFromImmutable`.
  /// </summary>
  SemanticVarFromImmutable = 3078,
  /// <summary>
  /// An 'enum' declares a case with associated values. Cases with payloads make it a 'union'.
  /// </summary>
  SemanticEnumCannotHaveAssociatedValues = 3079,
  /// <summary>
  /// A match arm binds a case's payload values and then never reads them. Drop the bindings, or use them.
  /// </summary>
  SemanticMatchDiscardedBindings = 3081,
  /// <summary>
  /// a labeled control-flow block (`if`/`else`/`while`/`for`) has no
  /// statements between its header and matching `end`. The C# bootstrap
  /// rejects this so dead control-flow can't sneak past a refactor; emitted
  /// from `parseBodyOrEmpty` after `parseScopedStatements` reports no
  /// statements were consumed.
  /// </summary>
  SemanticEmptyBlock = 3082,
  /// <summary>
  /// a block-form `try 'label' ... end` body contains no throwing
  /// calls (no bare throwing call/methodCall, no routed `throw`). The
  /// construct exists to funnel multiple throwing calls into one handler;
  /// a body that can never fail has no error to route, so the `otherwise`
  /// handler is dead. Mirrors the C# bootstrap's `SemanticTryBlockNoThrows`.
  /// </summary>
  SemanticTryBlockNoThrows = 3083,
  /// <summary>
  /// the `otherwise (e) 'label' ... end` handler of a block-form
  /// try must contain a `match` on the error binding `e`. Without it, the
  /// synthesized (possibly union) error value is never inspected and the
  /// handler cannot dispatch on which error occurred. Mirrors the C#
  /// bootstrap's `SemanticTryBlockBindingNotMatched`.
  /// </summary>
  SemanticTryBlockBindingNotMatched = 3084,
  /// <summary>
  /// a bare case-name pattern in a match on a synthesized error
  /// union is shared by two or more union members, so it is ambiguous --
  /// the user must qualify it as `EnumName.case`. Mirrors the C#
  /// bootstrap's `SemanticUnionMatchPatternAmbiguous`.
  /// </summary>
  SemanticUnionMatchPatternAmbiguous = 3085,
  /// <summary>
  /// a struct literal omits a field that has no default value, is not a
  /// compiler-synthesized managed builtin, and (for a return-site `Self{...}`
  /// in a static factory) was not proven definitely assigned via `self.field =
  /// expr` on every control-flow path to the literal. Emitted from the parser's
  /// struct-literal field-init checks and the post-body definite-assignment
  /// dataflow pass.
  /// </summary>
  SemanticFieldNotInitialized = 3086,
  /// <summary>
  /// an `if x.contains(k)` whose then-block immediately performs
  /// `try x.get(k) otherwise ...` on the same receiver/key pair does the
  /// lookup twice. The compiler asks the user to rewrite as `if let v =
  /// try x.get(k) ... 'lbl'` (or `if var`) so a single lookup serves both
  /// the membership test and the value bind.
  /// </summary>
  SemanticRedundantContainsGet = 3087,
  /// <summary>
  /// A 'module'-visible symbol is accessed from outside its declaring directory subtree.
  /// Symbol declared with the `module` keyword (visible to the declaring directory
  /// subtree only) but accessed from outside that subtree.
  /// </summary>
  SemanticSymbolNotInModuleScope = 3088,
  /// <summary>
  /// `==`/`!=` against an enum/union value's `.name`, `.ordinal`, or
  /// `.rawValue` accessor. Such a comparison is checking which case a value
  /// is, which must be done on the value itself (`value == Type.case` for a
  /// payload-free case, or `match value` for a union variant -- so adding a
  /// case forces every site to handle it instead of silently slipping
  /// through). Comparing the derived string/int accessor bypasses that.
  /// 3089-3096 are taken on the self-hosted side (semanticTypeResolutionLeak
  /// onward), so this shared diagnostic takes the next code free on both
  /// sides. Mirrors the C# bootstrap's `SemanticEnumAccessorComparison`.
  /// </summary>
  SemanticEnumAccessorComparison = 3097,
  /// <summary>
  /// A promise is stored in a Promise type that does not name the error its thunk throws.
  /// `Promise` is parameterised by BOTH what its thunk returns and what its thunk throws:
  /// `Promise with T` is a NON-throwing promise, `Promise with (T, E)` one that throws E.
  /// Storing a promise in the wrong one is refused here -- including, in particular, storing
  /// a THROWING promise in a `Promise with T`, which is what used to erase the error type.
  /// That erasure was the root of a family of bugs, all of which this refusal (plus the
  /// two-parameter form that makes it avoidable) turns into impossibilities:
  /// - `otherwise (e)` had no type to give `e`, and silently handed back the raw i64
  /// promise handle typed `int`;
  /// - an associated-value error's payload had no static type to mm_decref, so it LEAKED
  /// (only a runtime `errorIsHeapPtr` bit in the box approximated the answer);
  /// - propagation (a bare `try await p` inside a `throws` function) had no error type to
  /// check the enclosing function's `throws` against, so a thunk throwing A could be
  /// awaited inside a function throwing B and A's ordinals reinterpreted as B's tags.
  /// The fix a diagnostic can name is the point: it says which two-parameter type to write.
  /// </summary>
  SemanticPromiseErrorTypeMismatch = 3098,
  /// <summary>
  /// A closure that CAPTURES, ESCAPING the frame its captures point into.
  /// THE RULE: a closure that captures may not escape its defining frame.
  /// A closure captures BY REFERENCE: LowerClosureCreate allocates an environment and
  /// fills it with the ADDRESSES of the enclosing frame's stack slots, so that reads
  /// through a capture see later mutations of the captured variable. The environment is
  /// therefore only meaningful while that frame is alive. Let the closure outlive the
  /// frame and every captured read dereferences a dead frame -- the classic upward-funarg
  /// problem. It compiles clean and dies at runtime, so it is refused where the mistake
  /// is still legible rather than left to fault inside emitted code the author never wrote.
  /// The routes refused are every store the parser can see WITHOUT interprocedural
  /// analysis:
  /// - RETURNING one out of the frame that built it (`makeAdder` -- the common idiom, and
  /// the reason this exists). Returning a closure an OUTER frame built is fine and is
  /// allowed: that environment points into a frame that is still alive.
  /// - storing one in a struct FIELD, a GLOBAL/static, a CONTAINER (array/map literal)
  /// element, a union's associated-value PAYLOAD, or through a PAYLOAD BINDING (which
  /// looks like a plain local but is an alias INTO the enum's heap box, so assigning
  /// through it writes back). Each is one 8-byte slot holding the code pointer alone,
  /// and each is heap memory outliving every frame, so the store drops the environment;
  /// the call then passes env=0 and the first captured read dereferences null.
  /// DELIBERATELY NOT REFUSED -- the interprocedural route: a capturing closure passed as a
  /// CALL ARGUMENT to a callee that then stores it (`Handler.create(function(n) gives n +
  /// bump)`), and symmetrically a capturing closure arriving as a call's RETURN value. At
  /// that store the value is a *parameter*, and whether it carries an environment is a fact
  /// about the CALLER -- deciding it needs a per-parameter escape summary propagated over
  /// the call graph, i.e. escape analysis proper. That is scoped OUT of the bootstrap and
  /// stays a runtime nil-deref. Passing a capturing closure DOWN to a callee that only
  /// CALLS it is perfectly safe and must keep working.
  /// A NON-capturing closure is unaffected and must keep working -- it lowers to a plain
  /// MaxonFunctionRefOp, has no environment to lose, and passes every check above BY
  /// CONSTRUCTION rather than by an exception carved for it. It is what a table of handlers
  /// or passes keyed by a struct field is built from.
  /// What would MAKE the refused routes work is escape analysis plus by-value (or boxed)
  /// capture, so a closure's environment outlives the frame that built it. That is a real
  /// language mechanism and it is DELIBERATELY DEFERRED here: adopting it would change the
  /// by-reference capture semantics the closure specs currently pin. shv2 schedules it at
  /// P1.5, where it co-lands with `async` -- a green-thread capture IS an escape.
  /// </summary>
  SemanticCapturingClosureEscapes = 3099,
  /// <summary>
  /// A promise is awaited a SECOND time. `await` is LINEAR: a promise is awaited exactly once.
  /// 3100 rather than 3099: E3099 is SemanticCapturingClosureEscapes, which landed on main while
  /// this was in review. Both of us picked "the next code free" and both of us were right, because
  /// the registry is written down TWICE -- here and in maxon-selfhosted/Compiler/ErrorCode.maxon --
  /// and neither copy sees the other's pending codes. Same disease as the promise's two bits, one
  /// level up. Keep the two files in step until there is only one of them.
  /// The thunk owns its result and HANDS IT OVER at the await -- that is the ownership model the
  /// language already has everywhere else. A second await would take a second +1 on a payload the
  /// thunk only ever owned once, and the two releases underflow the refcount and free it twice
  /// ("mm_decref: refcount underflow (already zero)"). It is not an error-handling bug and does
  /// not need a throwing thunk: a plain `async` returning a String double-frees identically.
  /// So the double-free is made UNREPRESENTABLE rather than fixed. The check is flow-sensitive --
  /// two awaits of the same promise in mutually exclusive branches are each the only await on
  /// their own path, and are allowed; what is refused is a second await REACHABLE from a first.
  /// </summary>
  SemanticPromiseAlreadyAwaited = 3100,
  /// <summary>
  /// A `throws` function is referenced as a VALUE (`let f = risky`). A function type cannot
  /// express `throws` -- the grammar is `function(T) returns U`, with no throws clause -- so the
  /// binding silently drops it, and there is no indirect try-call to carry it: `StdIndirectCallOp`
  /// has no ErrorFlag, unlike `StdTryCallOp`.
  /// Before this check the call was not merely unchecked, it was WRONG. The callee took the error
  /// return (ordinal in RDX, `xor rax, rax` in RAX); the indirect caller read RAX and ignored RDX,
  /// so the throw vanished and the caller received 0 -- the dummy -- as a normal result. `try` was
  /// bypassed entirely by round-tripping the function through a value.
  /// Refused rather than supported, on evidence: no spec, no stdlib file, and none of
  /// maxon-selfhosted's 191,487 lines ever wanted a throwing function value. Adding `throws` to
  /// the function-type grammar plus an indirect try-call ABI is a FEATURE, and would be built for
  /// nobody. If a real need appears, that is the shape -- and this code is what says so.
  /// </summary>
  SemanticThrowingFunctionAsValue = 3101,
  /// <summary>
  /// A `/` or `mod` has a divisor the compiler holds as the constant 0 (`a / 0`, `a mod 0`, a
  /// divisor that folded to 0, or the float `a / 0.0` and `a / -0.0` -- both of which give an
  /// infinity). Unlike a possibly-zero divisor -- which is a throwing operation handled with
  /// `try` (E3057) -- a provably-zero one is neither recoverable nor safe: it is a bug, rejected
  /// at compile time.
  /// </summary>
  SemanticDivisionByZero = 3103,
  /// <summary>
  /// `Array.resize` is called on an array whose ELEMENT TYPE IS MANAGED -- a struct, a `String`,
  /// a nested container, a boxed union. Such an element lives in the buffer as a refcounted
  /// POINTER, so the zeroed slots `resize` exposes are NULL: an absence, not a value. Maxon has
  /// no default constructor, so there is nothing correct to put there, and the array it hands
  /// back is one whose `count()` does not agree with its `get()` -- `count()` says N while
  /// `get(0)` throws. Refused at the call site, naming the element type.
  /// The refusal covers the WHOLE call and not only its growing half, because which half a
  /// `resize(n)` is cannot be known until it runs: `n` is compared against a length, and a
  /// compiler holds neither. The two halves therefore split by NAME. Growing supplies the element
  /// the type cannot invent -- `push(value)` appends one, `growFilled(newLength, value:)` grows to
  /// a length in one call -- and shrinking needs no element at all, so `truncate(newLength)` stays
  /// available for every element type. All three are stdlib/Array.maxon's, and BOTH compilers compile
  /// that file -- shv2 loads all of stdlib/ -- so the cures are the same
  /// on both. shv2's message text still names only `push`, which understates the other two.
  /// It is refused only where the element type is KNOWN. An element that is still an unbound
  /// type parameter is not: one generic body serves every instantiation, and the deliberately
  /// sparse slot tables in `stdlib/Map.maxon` and `stdlib/Set.maxon` are built exactly that way
  /// -- they track occupancy in a parallel `states` column and never read a slot they did not
  /// write. The layer where an unwritten slot is a defined state is `__ManagedMemory.setLength`,
  /// and it stays available.
  /// </summary>
  SemanticArrayResizeManagedElement = 3106,
  /// <summary>
  /// Two `test` declarations in one file carry names that SANITIZE to the same symbol. A test has
  /// two names -- the prose one the reporter prints, and the mangled `__test_&lt;sanitized&gt;` one that
  /// reaches the symbol table -- and the sanitizer maps every character outside [A-Za-z0-9_] to
  /// `_`, so `adds two` and `adds-two` collide even though they read differently.
  /// The message names BOTH prose names and the symbol they share, because the collision is
  /// invisible in either name alone.
  /// Refusing it is independently worth doing: two tests with the same DISPLAY name are
  /// unreportable -- a reader of the report cannot tell which one failed -- so this rejects the
  /// identical-prose case for its own reason, not merely as a symbol-table accident.
  /// </summary>
  SemanticDuplicateTestName = 3107,
  /// <summary>
  /// A `test` declaration needs something from `stdlib/Testing.maxon` that this compile cannot
  /// see. Two symbols there are reachable WITHOUT the author naming them: `TestFailure`, which
  /// every `test` implicitly throws, and `__TestReport`, which the handler the compiler
  /// synthesizes for an uncaught foreign error reports through.
  /// Because neither name is written by the program, neither can be a misspelling -- so the
  /// message names the missing symbol AND the file that has to supply it, rather than reporting
  /// an unknown type or an unknown function at a line whose source mentions neither.
  /// ONE code for both, because it is one condition seen from two sides: a compile whose Testing
  /// module is absent or truncated. Two codes would let a reader fix half the cause and meet the
  /// other half on the next build.
  /// </summary>
  SemanticTestingStdlibUnavailable = 3108,
  /// <summary>
  /// A function's `throws` clause names something that is not a declared enum or union.
  /// The error-flag ABI carries a caught error as `ordinal + ErrorFlagOrdinalBias` for a payload-free
  /// enum and as a heap BOX POINTER for a payload-carrying union, and which of the two it is comes
  /// off the DECLARED clause at the catch site while the throw site derives it from the value it
  /// actually throws. A clause naming anything with no declared cases -- an INTERFACE (`throws Error`),
  /// a struct, or a name that resolves to nothing at all -- leaves those two derivations free to
  /// disagree: `throws Error` throwing a payload-carrying union was decoded as an ordinal and the box
  /// was never released (exit 101, a leak, in BOTH compilers before this check existed).
  /// It is a rule about a FUNCTION's own clause, not about an interface REQUIREMENT's: a requirement
  /// whose `throws` names an interface is the abstract error channel `Error` exists for, is dispatched
  /// through the witness ABI, and is guarded separately by E3016.
  /// </summary>
  SemanticThrowsTypeNotAnErrorEnum = 3113,
  /// <summary>
  /// A `try` on a call dispatched through an interface requirement whose `throws` names an INTERFACE
  /// (the abstract error channel, `throws Error`) asks for the caught error in a form that needs the
  /// error's CONCRETE type -- an `(e)` binding, or routing into a `try` BLOCK's shared handler.
  /// There is no such type at the dispatch. E3016 lets each conformer NARROW an abstract requirement
  /// to its own payload-free error enum, so the ordinal in the error flag means whatever the conformer
  /// that actually ran says it means, and which conformer that is becomes knowable only at
  /// monomorphization -- long after the parser decides everything a `try` decides.
  /// MEASURED before this check existed: the binding fell through to the raw error-flag `int`, and
  /// `print("{e}")` on a caught `ParseFailure.worse` printed `2` -- the ABI's `ordinal +
  /// ErrorFlagOrdinalBias`, handed to the user as their error value, compiling and running green. A
  /// `match e` on the same binding was refused instead, with `E2004: Expected pattern value`, naming a
  /// case the user had just written. The `try` BLOCK form failed a third way: nothing routed the call,
  /// so the block was refused with E3083 (`try block contains no throwing calls`) about a block that
  /// contains one.
  /// The forms that need no concrete type are unaffected and stay legal: `otherwise &lt;default&gt;`,
  /// `otherwise ignore`, `otherwise panic`, `otherwise return/break/continue`, and an `otherwise
  /// 'label'` block with no binding. Each catches the flag without decoding it, which is exactly what
  /// an abstract channel can promise. Bind the error by declaring the requirement as the concrete
  /// error enum the caller means to catch.
  /// NOT E3113, which is the same hazard on a FUNCTION's own clause and is refused at the DECLARATION.
  /// A requirement is allowed to name an interface -- that is what `Error` is for -- so the refusal
  /// has to fall on the catch site that cannot be served, not on the declaration that is well-formed.
  /// </summary>
  SemanticAbstractRequirementErrorNotBindable = 3123,
  /// <summary>
  /// `if try f()` was written on a call that PRODUCES a value. The bare form is a THROW test, not a
  /// value test -- the then branch runs whenever the call did not throw -- so the result it produces is
  /// silently dropped and the form reads as though it were being tested. `if try json.getBool(node,
  /// key: "enabled")` reads as "if enabled" and means "if the key exists and is a bool", which is true
  /// when the value is `false`. MEASURED before this check existed: a throwing `answer(succeed bool)
  /// returns bool` whose SUCCESS path returns `false` still took the branch.
  /// ONE law, not a type-keyed one: if the call produces a value you must say what happens to it, so
  /// `if try` is legal only when the callee returns nothing -- "run this, branch on whether it worked".
  /// An IMPURE callee's result may be discarded explicitly, `if let _ = try f()`. A PURE one's may not:
  /// `_` is E3064 there as everywhere, because a pure call whose result nobody wants is the wrong call.
  /// NOT E3055, which refuses a `try` whose callee cannot throw at all -- a different fault with a
  /// different cure, and this one fires only once that question has already been answered.
  /// </summary>
  SemanticIfTryDiscardsResult = 3124,

  /// <summary>
  /// The IR builder met an expression form it cannot lower.
  /// </summary>
  IrUnsupportedExpression = 4001,
  /// <summary>
  /// A field access could not be lowered: the base is not a struct, or the field has no slot.
  /// </summary>
  IrInvalidFieldAccess = 4006,
  /// <summary>
  /// A method call could not be lowered.
  /// </summary>
  IrInvalidMethodCall = 4007,
  /// <summary>
  /// a type definition contains a reference cycle -- it transitively
  /// contains itself through struct fields, union associated values, or
  /// container element types. Maxon's ownership model requires acyclic type
  /// graphs for deterministic destruction, so recursive type references are
  /// rejected. Emitted by the type-cycle check after type resolution. Mirrors
  /// the C# bootstrap's `IrTypeCycle` (same code, same message format).
  /// </summary>
  IrTypeCycle = 4014,

  /// <summary>
  /// `--coverage` was combined with `--no-debug-info`. The instrumented binary's counters are
  /// anonymous numbers: what each one counts lives in the `.mxdbg` sidecar's coverage-point
  /// table, which `--no-debug-info` suppresses. Emitting them anyway would produce a `.mxcov`
  /// data file nothing could ever interpret, so the combination is refused rather than silently
  /// dropping either half.
  /// </summary>
  CodeEmitterCoverageNeedsDebugInfo = 5003,
  /// <summary>
  /// The requested target is one this compiler cannot write an executable for. maxon-sharp ships a
  /// PE writer and a Mach-O writer and no others, so the pairs it can emit are exactly x64-windows
  /// and arm64-macos.
  /// Refused rather than approximated, because the approximation was silent and wrong: the object
  /// writer used to be chosen by ARCHITECTURE alone, so `--target=x64-linux` reached the PE writer
  /// and exited 0 having produced a WINDOWS executable whose stdlib had been parsed with
  /// `#if os(Linux)` taken -- POSIX semantics inside a PE. `arm64-linux` and `arm64-windows` reached
  /// the Mach-O writer the same way, the latter writing a Mach-O named `.exe`.
  /// The DEFAULT target is checked too, not only an explicit `--target=`: the default is the host,
  /// which on a Linux box is x64-linux, so a plain `maxon build` there produced a PE as well.
  /// Source-level Linux awareness is unaffected and deliberately kept -- `#if os(Linux)` remains a
  /// legal predicate the parser evaluates. What is withdrawn is the claim to EMIT for it.
  /// </summary>
  CodeEmitterUnsupportedTarget = 5004,

  /// <summary>
  /// The previous build output at this path could not be removed before the build began, so this
  /// build cannot replace it -- it is locked (on Windows a RUNNING executable cannot be deleted)
  /// or read-only. Refused up front rather than at the write, because the write is logged and
  /// swallowed: carrying on would print "Wrote N bytes" and exit 0 over an untouched STALE binary,
  /// which is the exact confident-wrong-answer this deletion exists to prevent.
  /// The message names the LIKELY cause as well as the mechanical one: in practice the holder is a
  /// spec-test or a build of this same tree that has not exited yet, and the compiler cannot
  /// identify it (that would need RestartManager/NtQuerySystemInformation, imported nowhere here).
  /// It also states that the previous binary SURVIVED -- this is the one branch where a failed build
  /// leaves an output behind, so a `;`-chained build-then-test runs the stale one. The wait-or-kill
  /// deadline it quotes is `WedgeWatchdogMs` (maxon-shv2/Testing/SpecWorkerPool.maxon), read from
  /// the constant so the message and the watchdog cannot disagree.
  /// </summary>
  BinaryOutputNotReplaceable = 6002,

  /// <summary>
  /// An internal compiler invariant was violated. This is a compiler bug.
  /// </summary>
  InternalError = 9001,
}
