#!/usr/bin/env python3
"""generate-seed-language-shim.py - write the seed shim that withdraws every language form the seed
cannot parse.

Three forms: a `typealias ... implements` clause, a generic function (`function f(...) uses T`), and
a type body's inferred field (`var x = e as T`, `var x = Type.member(...)`, `var x = "text"`, which
the seed reads only as `var x as T = e`). The seed enforces every ranged typealias nominally, so
once the clauses are gone each widening crossing the tree relies on is an E3005/E2028 there; a
generic function is withdrawn whole, which the tree affords because the compiler calls none; an
inferred field is written back with the type its initializer names. This script copies the tree's
`maxon-bin/`, `stdlib/` and `runtime/` into a scratch directory, stages every other patch in
`scripts/seed-shim/` in sorted order, strips all three forms, and then builds with the seed until
it is clean, writing at every site the seed refuses the cast to the parent it names: on each arm of
a match whose arms disagree, after an `otherwise` fallback, and, where one operand of a binary
operator is a number literal, on the other operand, cast to the literal's alias. A cast the seed
calls unneeded (E3010) is dropped. A `Compiler.`-qualified name is written bare, which the seed
resolves to the same declaration; an E3078 its borrow checker raises gets the `.clone()` it asks
for, and a loop it reads as still borrowing what its body mutates iterates a clone held in a local;
a decimal integer literal above i64.max is written in hex, and a typealias range bound above it as
i64.max. The difference is the patch.

Usage:
  python scripts/seed-shim/generate-seed-language-shim.py [--tree DIR] [--seed PATH] [--work DIR]
      [--output PATH] [--resume]

--work must be empty, and defaults to a fresh system temp directory; with --resume it is the
directory a previous run left, and the build loop continues there. Keep it outside the checkout,
whose `temp/` carries a `.maxonignore`. --output defaults to the committed patch in
`scripts/seed-shim/`.

Exit codes: 0 the patch was written; 1 the tree holds what this script cannot shim: an integer
literal it cannot rewrite in a form the seed lexes, a `Compiler.` qualifier it cannot write bare
without changing the declaration it names, a field default with no inferable type, or a seed refusal
it does not cast, including a loop it cannot prove leaves its iterated collection unmutated.
"""
import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "library-cache"))

from maxon_source import FieldDefaultShapeError, field_default_type

PATCH_NAME = "0016-withdraw-the-language-forms-the-seed-cannot-parse-from-the-first-build.patch"
SOURCE_DIRS = ["maxon-bin", "stdlib", "runtime"]
MAX_ROUNDS = 800
MAX_ATTEMPTS_PER_SITE = 10

HEADER = """# The seed cannot parse a generic function, so each is withdrawn whole; the compiler calls none of them.
# The seed cannot parse a `typealias X = int(range) implements Parent` clause either, and it enforces every ranged
# typealias nominally at every crossing. Each clause is withdrawn, and every place the tree widens a subtype
# to its parent without a cast gets the cast the seed names. A divisor cast to a parent that admits 0 makes the
# division throwing to the seed, so it is written `try (…) otherwise panic`; the tree proved it nonzero.
# The seed cannot infer a field's type from its initializer, so each type-body `var x = e as T`, `var x = Type.member(...)`
# and `var x = "text"` is written `var x as T = e`.
# The seed cannot lex a decimal integer literal above i64.max, so each is written in hex, and a typealias range bound is
# written i64.max.
# The declarations, their ranges and every table stay, so `C1` knows the clause and compiles the unshimmed tree
# into `C2`. An `export` whose only reach beyond its file was through such a crossing is an E3092 to the seed
# once the crossing is a cast, so it is withdrawn too.
# The seed cannot parse a `Compiler.`-qualified name, so each is written bare; the seed resolves that to the same
# declaration. Where its older borrow checker refuses a legal program, the patch writes the copy it demands: the
# `.clone()` an E3078 names, and a clone held in a local for a loop it reads as borrowing what its body mutates.
# GENERATED by `scripts/seed-shim/generate-seed-language-shim.py`; regenerate it when the sources it touches move.
"""

DECLARATION = re.compile(r"^(?P<head>(?:[a-z]+ )*typealias (?P<name>[A-Za-z0-9_]+) = [^\r\n]*?) implements (?P<parent>[A-Za-z0-9_]+)[ \t]*(?P<eol>\r?)$", re.M)
GENERIC_FUNCTION = re.compile(r"^(?P<indent>[ \t]*)(?:[a-z]+ )*function (?P<name>[A-Za-z0-9_]+)\(.*\) uses [A-Z][^\r\n]*$")
RANGE_DECLARATION = re.compile(r"^(?:[a-z]+ )*typealias (?P<name>[A-Za-z0-9_]+) = int\((?P<range>[^)\r\n]*)\)", re.M)
RANGE_UPPER_BOUND_PREFIX = re.compile(r"^[ \t]*(?:[a-z]+ )*typealias [A-Za-z0-9_]+ = int\([^)]* to $")
WIDE_DECIMAL_LITERAL = re.compile(r"(?<![A-Za-z0-9_.])(?P<digits>[0-9]{19,20})(?![A-Za-z0-9_.])")
DIAGNOSTIC = re.compile(r"^error (?P<code>E\d+): (?P<path>.+?):(?P<line>\d+):(?P<column>\d+): (?P<message>.*)$")
BINARY = re.compile(r"^operator '(?P<op>[^']+)' requires both operands to be the same type: '(?P<left>[A-Za-z0-9_]+)' and '(?P<right>[A-Za-z0-9_]+)' are different typealiases")
MISMATCH = re.compile(r"^type mismatch: 'expected (?P<expected>[A-Za-z0-9_]+), got (?P<got>[A-Za-z0-9_]+)'")
MATCH_ARMS = re.compile(r"^match arms give incompatible types: '(?P<first>[A-Za-z0-9_]+)' vs '(?P<second>[A-Za-z0-9_]+)'")
UNNEEDED_CAST = re.compile(r"^unneeded cast: '(?P<source>[A-Za-z0-9_]+)' already fits in '(?P<target>[A-Za-z0-9_]+)'")
OTHERWISE = re.compile(r"^type mismatch: 'otherwise type '(?P<got>[A-Za-z0-9_]+)' does not match expected type '(?P<expected>[A-Za-z0-9_]+)'")
TERNARY = re.compile(r"^ternary expression type mismatch: true branch is '(?P<whenTrue>[A-Za-z0-9_]+)' but false branch is '(?P<whenFalse>[A-Za-z0-9_]+)'")
UNUSED_EXPORT = re.compile(r"^exported [a-z]+ '(?P<name>[A-Za-z0-9_]+)' is never referenced outside its declaring file")
ARGUMENT = re.compile(r"^argument type mismatch for '(?P<label>[A-Za-z0-9_]+)': expected '(?P<expected>[A-Za-z0-9_]+)', got '(?P<got>[A-Za-z0-9_]+)'")
IMMUTABLE_TO_MUTABLE = re.compile(r"^cannot assign immutable variable '(?P<source>[A-Za-z0-9_]+)' to mutable binding '(?P<target>[A-Za-z0-9_]+)'; .*use clone\(\)")
BORROWED_BY_LOOP = re.compile(r"^cannot mutate '(?P<owner>[A-Za-z0-9_]+)' via '(?P<via>[A-Za-z0-9_]+)' while it is borrowed by '(?P<element>[A-Za-z0-9_]+)' \(borrowed at line (?P<line>\d+)\)")
FOR_LOOP = re.compile(r"^(?P<indent>[ \t]*)for (?P<element>[A-Za-z0-9_]+) in (?P<iterated>.+?) (?P<label>'[A-Za-z0-9_]+')(?P<eol>\r?)$")
CLONE_CALL = ".clone()"
HELD_PREFIX = "seedHeld"
PROVEN_LOOP_HOISTS = {
	("maxon-bin/Compiler/Parser.maxon", "'eachCandidate'", "self.signatures.overloadedDeclsOf(callee)", "signatures", "slotTypeThroughCallReceiver"): "44f273abe7bed010dabdfb1805f7ab19f3b34d24066d5312fcdf4b5159bd2c89",
}
FIELD = re.compile(r"^cannot assign a value of type '(?P<got>[A-Za-z0-9_]+)' to (?:field|variable) '(?P<field>[A-Za-z0-9_]+)'(?: of '[A-Za-z0-9_]+')?, which holds '(?P<expected>[A-Za-z0-9_]+)'")

AUTHOR_SOURCE_DIR = "maxon-bin"
NAMESPACE_ROOT = "Compiler"
NAMESPACE_QUALIFIER = NAMESPACE_ROOT + "."
QUALIFIED = re.compile(re.escape(NAMESPACE_QUALIFIER) + r"[A-Z][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*")
DECLARED_NAME = re.compile(r"^(?:[a-z]+ )*(?:type|enum|union|typealias|interface|function|let|var) (?P<name>[A-Za-z_][A-Za-z0-9_]*)", re.M)

SELF = "self"
MEMBER_CHAIN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*")
ASSIGNMENT = re.compile(r"\s*[-+*/%]?=(?!=)")
STDLIB_DIR = "stdlib"
COLLECTION_TYPES = {"Array", "List", "Map", "Set", "Vector"}
READ_ONLY_COLLECTION_METHODS = {"capacity", "clone", "contains", "count", "equals", "first", "get", "getCapacity", "hash", "isEmpty", "last", "slice"}
MEMBER_DECLARATION = re.compile(r"^[ \t]*(?:[a-z]+ )*(?:function|let|var) (?P<name>[A-Za-z_][A-Za-z0-9_]*)", re.M)
TOP_LEVEL_DECLARATION = re.compile(r"^(?:[a-z]+ )*(?P<keyword>type|extension|interface|enum|union|function|typealias|let|var) (?P<name>[A-Za-z_][A-Za-z0-9_]*)")

TYPE_BODY_OPENER = re.compile(r"^(?P<indent>\t*)(?:[a-z]+ )*(?P<keyword>type|function) ")
BLOCK_CLOSE = re.compile(r"^(?P<indent>\t*)end '")
FIELD_DECLARATION = re.compile(r"^(?P<indent>\t+)(?P<modifiers>(?:[a-z]+ )*)(?:var|let) (?P<name>[A-Za-z_][A-Za-z0-9_]*)(?P<separator> = )(?P<value>.*)$")
BARE_LITERAL = re.compile(r"^(?:true|false|-?(?:0x[0-9A-Fa-f_]+|[0-9][0-9_]*(?:\.[0-9][0-9_]*)?))$")
STATIC_MODIFIER = "static"
TYPE_KEYWORD = "type"

KEYWORDS = {"if", "else", "while", "return", "not", "and", "or", "then", "gives", "let", "var", "for", "in", "upto", "downto", "match", "try", "otherwise", "throw", "as"}
IDENT = re.compile(r"[A-Za-z0-9_]")
OPENERS = {"(": ")", "[": "]", "{": "}"}
CLOSERS = {v: k for k, v in OPENERS.items()}
OPERATOR_LEVEL = {"+": 1, "-": 1, "*": 2, "/": 2, "%": 2, "mod": 2}
COMPARISON = {"==", "!=", "<", "<=", ">", ">="}
DIVISION_WITHOUT_TRY = re.compile(r"^throwing division requires try")
DIVISION_OPERATORS = ["/", "mod"]
RANGE_KEYWORDS = ("upto", "downto")
SEED_INT_LITERAL_MAX = 2**63 - 1
U64_MAX = 2**64 - 1
SEED_RANGE_MAX = "i64.max"
ARM_SEPARATOR = " gives "
OTHERWISE_KEYWORD = " otherwise "
NUMBER_LITERAL = re.compile(r"-?[0-9][0-9_]*(?:\.[0-9][0-9_]*)?")
CAST_SUFFIX = re.compile(r"\s+as\s+[A-Za-z_][A-Za-z0-9_.]*")
MULTIPLICATIVE_OPERATORS = ["*", "/", "%", " mod"]
DIVISOR_NEVER_ZERO = "the tree's divisor type excludes 0; only the cast to its parent admits it"


class Unhandled(Exception):
	pass


def run(args, cwd, check=True):
	result = subprocess.run(args, cwd=cwd, capture_output=True, text=True, encoding="utf-8", errors="replace")

	if check and result.returncode != 0:
		raise SystemExit(f"generate-seed-language-shim.py: {' '.join(args)} exited {result.returncode}\n{result.stdout}{result.stderr}")

	return result


def git(work, *args):
	return run(["git", "-c", "core.autocrlf=false", "-c", "user.name=shim", "-c", "user.email=shim@localhost", *args], cwd=work)


def stage_work(tree, work, seed, output):
	listed = run(["git", "ls-files", "-co", "--exclude-standard", "-z", "--", *SOURCE_DIRS], cwd=tree).stdout.split("\0")

	for rel in filter(None, listed):
		src = os.path.join(tree, rel)

		if not os.path.isfile(src):
			continue

		dst = os.path.join(work, rel)
		os.makedirs(os.path.dirname(dst), exist_ok=True)
		shutil.copyfile(src, dst)

	os.makedirs(os.path.join(work, ".bootstrap"), exist_ok=True)
	shutil.copy2(seed, os.path.join(work, ".bootstrap", os.path.basename(seed)))

	git(work, "init", "-q")

	with open(os.path.join(work, ".git", "info", "exclude"), "a", encoding="utf-8") as exclude:
		exclude.write("/.bootstrap/\n/maxon-bin/.maxon/\n/out/\n")

	shim_dir = os.path.join(tree, "scripts", "seed-shim")
	patches = sorted(p for p in os.listdir(shim_dir) if p.endswith(".patch"))

	for patch in patches:
		path = os.path.join(shim_dir, patch)

		if patch == PATCH_NAME or os.path.abspath(path) == os.path.abspath(output):
			continue

		git(work, "apply", "--", path)

	git(work, "add", "-A")
	git(work, "commit", "-q", "-m", "base")


def maxon_sources(work, directories):
	for directory in directories:
		for dirpath, _, files in os.walk(os.path.join(work, directory)):
			for name in sorted(files):
				if name.endswith(".maxon"):
					yield os.path.join(dirpath, name)


def collect_aliases(root):
	parents = {}
	ranges = {}

	for path in maxon_sources(root, SOURCE_DIRS):
		text = read(path)

		for m in DECLARATION.finditer(text):
			parents[m.group("name")] = m.group("parent")

		for m in RANGE_DECLARATION.finditer(text):
			ranges[m.group("name")] = m.group("range")

	return parents, ranges


def strip_clauses(work):
	stripped_count = 0

	for path in maxon_sources(work, SOURCE_DIRS):
		text = read(path)

		if " implements " not in text:
			continue

		stripped = DECLARATION.sub(lambda m: m.group("head") + m.group("eol"), text)

		if stripped != text:
			stripped_count += len(DECLARATION.findall(text))
			write(path, stripped)

	return stripped_count


def write_wide_literals_in_hex(work):
	rewritten_count = 0
	refused = []

	for path in maxon_sources(work, SOURCE_DIRS):
		text = read(path)

		if WIDE_DECIMAL_LITERAL.search(text) is None:
			continue

		lines = text.split("\n")

		try:
			regions = CodeRegions(lines).per_line
		except Unhandled as e:
			refused.append(f"{os.path.relpath(path, work)}: {e}")
			continue

		for index, line in enumerate(lines):
			out = []
			last = 0

			for start, end in regions[index]:
				for m in WIDE_DECIMAL_LITERAL.finditer(line, start, end):
					value = int(m.group("digits"))

					if value <= SEED_INT_LITERAL_MAX:
						continue

					if value > U64_MAX:
						refused.append(f"{os.path.relpath(path, work)}:{index + 1}: the literal {value} is wider than any integer type")
						continue

					out.append(line[last:m.start()])
					out.append(SEED_RANGE_MAX if RANGE_UPPER_BOUND_PREFIX.match(line[:m.start()]) else f"0x{value:X}")
					last = m.end()
					rewritten_count += 1

			out.append(line[last:])
			lines[index] = "".join(out)

		write(path, "\n".join(lines))

	return rewritten_count, refused


def strip_generic_functions(work):
	withdrawn = 0

	for path in maxon_sources(work, SOURCE_DIRS):
		lines = read(path).split("\n")
		kept = []
		i = 0
		changed = False

		while i < len(lines):
			m = GENERIC_FUNCTION.match(lines[i])

			if m is None:
				kept.append(lines[i])
				i += 1
				continue

			end = re.compile(r"^" + re.escape(m.group("indent")) + r"end '" + re.escape(m.group("name")) + r"'\r?$")
			close = next((j for j in range(i + 1, len(lines)) if end.match(lines[j])), None)

			if close is None:
				raise SystemExit(f"generate-seed-language-shim.py: {path}:{i + 1}: generic function '{m.group('name')}' has no `end '{m.group('name')}'`")

			while kept and kept[-1].lstrip().startswith("//"):
				kept.pop()

			i = close + 1

			if i < len(lines) and lines[i].strip() == "":
				i += 1

			withdrawn += 1
			changed = True

		if changed:
			write(path, "\n".join(kept))

	return withdrawn


class Lexeme:
	STRING = "string"
	BYTE_STRING = "byte string"
	QUOTED = "single-quoted literal"
	BLOCK_COMMENT = "block comment"
	FORMAT_SPECIFIER = "format specifier"
	INTERPOLATION = "interpolation"


class Interpolation:
	def __init__(self):
		self.kind = Lexeme.INTERPOLATION
		self.braces = 1
		self.groups = 0


class CodeRegions:
	def __init__(self, lines):
		self.stack = []
		self.per_line = []
		self.comments_per_line = []

		for number, line in enumerate(lines, start=1):
			self.per_line.append(self.lex_line(number, line))

		if self.stack:
			raise Unhandled(f"a {getattr(self.stack[-1], 'kind', self.stack[-1])} is still open at the end of the file")

	def in_code(self):
		return not self.stack or isinstance(self.stack[-1], Interpolation)

	def lex_line(self, number, line):
		regions = []
		comments = []
		start = 0 if self.in_code() else None
		comment_start = 0 if self.stack and self.stack[-1] == Lexeme.BLOCK_COMMENT else None
		continued = False
		i = 0

		def leave(at):
			nonlocal start

			if start is not None:
				regions.append((start, at))
				start = None

		while i < len(line):
			top = self.stack[-1] if self.stack else None
			c = line[i]

			if top is None or isinstance(top, Interpolation):
				if line.startswith("//", i):
					leave(i)
					comments.append((i, len(line)))
					i = len(line)
					break

				if line.startswith("/*", i):
					leave(i)
					comment_start = i
					self.stack.append(Lexeme.BLOCK_COMMENT)
					i += 2
					continue

				if c == '"':
					byte_string = i > 0 and line[i - 1] == "b" and (i < 2 or not IDENT.match(line[i - 2]))
					leave(i - 1 if byte_string else i)
					self.stack.append(Lexeme.BYTE_STRING if byte_string else Lexeme.STRING)
					i += 1
					continue

				if c == "'":
					leave(i)
					self.stack.append(Lexeme.QUOTED)
					i += 1
					continue

				if top is not None:
					if c == ":" and top.braces == 1 and top.groups == 0:
						leave(i)
						self.stack.append(Lexeme.FORMAT_SPECIFIER)
					elif c in "([":
						top.groups += 1
					elif c in ")]" and top.groups > 0:
						top.groups -= 1
					elif c == "{":
						top.braces += 1
					elif c == "}":
						top.braces -= 1

						if top.braces == 0:
							leave(i)
							self.stack.pop()

				i += 1
				continue

			if top == Lexeme.BLOCK_COMMENT:
				if line.startswith("*/", i):
					self.stack.pop()
					i += 2
					comments.append((comment_start, i))
					comment_start = None

					if self.in_code():
						start = i

					continue

				i += 1
				continue

			if top == Lexeme.FORMAT_SPECIFIER:
				if c == "}":
					self.stack.pop()
					self.stack.pop()

				i += 1
				continue

			if c == "\\":
				continued = i + 1 == len(line)
				i += 2
				continue

			closer = "'" if top == Lexeme.QUOTED else '"'

			if c == closer:
				self.stack.pop()
				i += 1

				if self.in_code():
					start = i

				continue

			if top == Lexeme.STRING and c == "{":
				self.stack.append(Interpolation())
				i += 1
				start = i
				continue

			i += 1

		leave(len(line))

		if comment_start is not None:
			comments.append((comment_start, len(line)))

		self.comments_per_line.append(comments)

		if self.stack and self.stack[-1] in (Lexeme.STRING, Lexeme.FORMAT_SPECIFIER) and not continued:
			raise Unhandled(f"line {number}: a {self.stack[-1]} is not closed on its line, which the Maxon lexer refuses")

		return regions

	def view(self, index, line):
		masked = [" "] * len(line)

		for start, end in self.per_line[index]:
			masked[start:end] = line[start:end]

		return "".join(masked)

	def uncommented(self, index, line):
		kept = list(line)

		for start, end in self.comments_per_line[index]:
			kept[start:end] = [" "] * (end - start)

		return "".join(kept)


class Namespaces:
	def __init__(self, work):
		self.root = os.path.normpath(os.path.join(work, AUTHOR_SOURCE_DIR))
		self.declarations = {}

		for path in maxon_sources(work, [AUTHOR_SOURCE_DIR]):
			directory = os.path.normpath(os.path.dirname(path))

			for m in DECLARED_NAME.finditer(read(path)):
				self.declarations.setdefault(m.group("name"), []).append(directory)

	def relative(self, directory):
		return os.path.relpath(directory, os.path.dirname(self.root)).replace("\\", "/")

	def unqualify(self, qualified):
		segments = qualified.split(".")
		directory = self.root

		for index, segment in enumerate(segments):
			sites = self.declarations.get(segment, [])
			subdirectory = os.path.join(directory, segment)
			names_a_directory = segment in os.listdir(directory) and os.path.isdir(subdirectory)

			if names_a_directory:
				if directory in sites:
					raise Unhandled(f"`{qualified}`: '{segment}' names both the directory {self.relative(subdirectory)} and a declaration in {self.relative(directory)}")

				directory = subdirectory
				continue

			if index == 0:
				raise Unhandled(f"`{qualified}`: '{segment}' is not a directory of {self.relative(directory)}")

			if len(sites) != 1:
				found = ", ".join(sorted(self.relative(site) for site in sites)) or "none"
				raise Unhandled(f"`{qualified}`: '{segment}' has {len(sites)} declarations among the {AUTHOR_SOURCE_DIR} sources ({found}), so its bare spelling is not one declaration to the seed")

			if sites[0] != directory:
				raise Unhandled(f"`{qualified}`: '{segment}' is declared in {self.relative(sites[0])}, not in {self.relative(directory)}")

			return ".".join(segments[index:])

		raise Unhandled(f"`{qualified}` names the directory {self.relative(directory)}, not a declaration")


def unqualify_code(line, regions, namespaces):
	out = []
	last = 0

	for start, end in regions:
		for m in QUALIFIED.finditer(line, start, end):
			if m.start() > 0 and (IDENT.match(line[m.start() - 1]) or line[m.start() - 1] == "."):
				continue

			out.append(line[last:m.start()])
			out.append(namespaces.unqualify(m.group(0)))
			last = m.end()

	out.append(line[last:])
	return "".join(out)


def strip_namespace_qualifiers(work):
	namespaces = Namespaces(work)
	unqualified = 0
	refused = []

	for path in maxon_sources(work, SOURCE_DIRS):
		text = read(path)

		if NAMESPACE_QUALIFIER not in text:
			continue

		lines = text.split("\n")
		rewritten = []

		try:
			regions = CodeRegions(lines).per_line
		except Unhandled as e:
			refused.append(f"{os.path.relpath(path, work)}: {e}")
			continue

		for line_number, line in enumerate(lines, start=1):
			try:
				rewritten.append(unqualify_code(line, regions[line_number - 1], namespaces))
			except Unhandled as e:
				refused.append(f"{os.path.relpath(path, work)}:{line_number}: {e}")
				rewritten.append(line)

		unqualified += sum(1 for a, b in zip(lines, rewritten) if a != b)

		if rewritten != lines:
			write(path, "\n".join(rewritten))

	return unqualified, refused


def field_annotation(value):
	if BARE_LITERAL.fullmatch(value):
		return None

	try:
		return field_default_type(value)
	except FieldDefaultShapeError as e:
		raise Unhandled(str(e))


def annotate_inferred_fields(work):
	annotated = 0
	refused = []

	for path in maxon_sources(work, SOURCE_DIRS):
		text = read(path)
		lines = text.split("\n")

		try:
			regions = CodeRegions(lines)
		except Unhandled as e:
			refused.append(f"{os.path.relpath(path, work)}: {e}")
			continue

		enclosing = []

		for index, line in enumerate(lines):
			close = BLOCK_CLOSE.match(line)

			if close:
				depth = len(close.group("indent"))
				enclosing = [entry for entry in enclosing if entry[0] < depth]
				continue

			field = FIELD_DECLARATION.match(line)

			if field and enclosing and enclosing[-1] == (len(field.group("indent")) - 1, TYPE_KEYWORD) and STATIC_MODIFIER not in field.group("modifiers").split():
				comments = regions.comments_per_line[index]
				value_start = field.start("value")
				value_end = min((start for start, _ in comments), default=len(line))
				value = line[value_start:value_end].rstrip()
				value_end = value_start + len(value)

				try:
					inferred = field_annotation(value)
				except Unhandled as e:
					refused.append(f"{os.path.relpath(path, work)}:{index + 1}: {e}")
					continue

				if inferred is not None:
					target, initializer = inferred
					lines[index] = line[:field.end("name")] + f" as {target}" + line[field.end("name"):value_start] + initializer + line[value_end:]
					annotated += 1

				continue

			opener = TYPE_BODY_OPENER.match(line)

			if opener:
				enclosing.append((len(opener.group("indent")), opener.group("keyword")))

		rewritten = "\n".join(lines)

		if rewritten != text:
			write(path, rewritten)

	return annotated, refused


def read(path):
	with open(path, "r", encoding="utf-8", newline="") as f:
		return f.read()


def write(path, text):
	with open(path, "w", encoding="utf-8", newline="") as f:
		f.write(text)


def ancestors(parents, name):
	chain = [name]

	while chain[-1] in parents:
		chain.append(parents[chain[-1]])

	return chain


def common_ancestor(parents, left, right):
	right_chain = ancestors(parents, right)

	for candidate in ancestors(parents, left):
		if candidate in right_chain:
			return candidate

	raise Unhandled(f"'{left}' and '{right}' share no ancestor through an `implements` clause")


def require_widening(parents, got, expected):
	if expected not in ancestors(parents, got)[1:]:
		raise Unhandled(f"'{got}' does not implement '{expected}', so no widening cast answers this")


def match_back(line, close_index):
	depth = 0
	closer = line[close_index]
	opener = CLOSERS[closer]

	for i in range(close_index, -1, -1):
		if line[i] in "\"'":
			raise Unhandled("a string literal inside the operand")

		if line[i] == closer:
			depth += 1
		elif line[i] == opener:
			depth -= 1

			if depth == 0:
				return i

	raise Unhandled("unbalanced brackets before the operator")


def match_forward(line, open_index):
	depth = 0
	opener = line[open_index]
	closer = OPENERS[opener]
	i = open_index

	while i < len(line):
		c = line[i]

		if c == '"':
			i = line.index('"', i + 1)
		elif c == opener:
			depth += 1
		elif c == closer:
			depth -= 1

			if depth == 0:
				return i

		i += 1

	raise Unhandled("unbalanced brackets after the operator")


def atom_before(line, end):
	i = end

	while i > 0 and line[i - 1] == " ":
		i -= 1

	stop = i

	while i > 0:
		if line[i - 1] in CLOSERS:
			i = match_back(line, i - 1)

		j = i

		while j > 0 and IDENT.match(line[j - 1]):
			j -= 1

		if line[j:i] not in KEYWORDS:
			i = j

		if i > 0 and line[i - 1] == "." and i < stop:
			i -= 1
			continue

		break

	if i == stop:
		raise Unhandled("no operand before the operator")

	return i, stop


def atom_after(line, start):
	i = start

	while i < len(line) and line[i] == " ":
		i += 1

	begin = i

	if i < len(line) and line[i] == "-":
		i += 1

	if i < len(line) and line[i] in OPENERS:
		i = match_forward(line, i) + 1
	else:
		j = i

		while j < len(line) and IDENT.match(line[j]):
			j += 1

		if j == i or line[i:j] in KEYWORDS:
			raise Unhandled("no operand after the operator")

		i = j

	while i < len(line):
		if line[i] in "([{":
			i = match_forward(line, i) + 1
		elif line[i] == "." and i + 1 < len(line) and IDENT.match(line[i + 1]):
			i += 1

			while i < len(line) and IDENT.match(line[i]):
				i += 1
		else:
			break

	return begin, i


def operator_level(op):
	if op in COMPARISON:
		return 0

	return OPERATOR_LEVEL.get(op)


def binary_operand_before(line, end, op):
	start, stop = atom_before(line, end)
	level = operator_level(op)

	if level is None:
		return start, stop

	while True:
		i = start

		while i > 0 and line[i - 1] == " ":
			i -= 1

		prior = next((a for a in OPERATOR_LEVEL if line[:i].endswith(" " + a) and OPERATOR_LEVEL[a] >= level), None)

		if prior is None:
			return start, stop

		start, _ = atom_before(line, i - len(prior))


def binary_operand_after(line, start, op):
	begin, end = atom_after(line, start)
	level = operator_level(op)

	if level is None:
		return begin, end

	while True:
		rest = line[end:]
		following = next((a for a in OPERATOR_LEVEL if rest.startswith(" " + a + " ") and OPERATOR_LEVEL[a] > level), None)

		if following is None:
			return begin, end

		_, end = atom_after(line, end + len(following) + 2)


def statement_value(line, start):
	i = start
	depth = 0

	while i < len(line):
		c = line[i]

		if c == '"':
			i = line.index('"', i + 1)
		elif c in OPENERS:
			depth += 1
		elif c in CLOSERS:
			if depth == 0:
				break

			depth -= 1
		elif c == "," and depth == 0:
			break
		elif c == "'" and depth == 0:
			break

		i += 1

	end = i

	while end > start and line[end - 1] in " \r":
		end -= 1

	if end == start:
		raise Unhandled("no value to cast")

	return start, end


def cast(line, start, end, target):
	inner = line[start:end]

	if re.fullmatch(r"\([A-Za-z0-9_.]+\)", inner):
		inner = inner[1:-1]
	elif not is_member_chain(inner):
		inner = f"({inner})"

	return line[:start] + f"({inner} as {target})" + line[end:]


def find_operand(find, line, position, op):
	try:
		return find(line, position, op)
	except Unhandled as e:
		return e


def operand_text(line, span):
	if isinstance(span, Unhandled):
		return ""

	return line[span[0]:span[1]]


def require_operand(span):
	if isinstance(span, Unhandled):
		raise span

	return span


def require_castable(parents, ranges, source, target):
	if source == target or target in ancestors(parents, source)[1:]:
		return

	if source in ranges and ranges[source] == ranges.get(target):
		return

	raise Unhandled(f"'{source}' neither implements '{target}' nor shares its range, so casting to it could change a value")


def cast_match_arms(lines, line_number, message, parents):
	m = MATCH_ARMS.match(message)
	target = ancestors(parents, common_ancestor(parents, m.group("first"), m.group("second")))[-1]
	opener = lines[line_number - 1]
	indent = re.match(r"\t*", opener).group(0)
	label = re.search(r"'[A-Za-z0-9_]+'\r?$", opener)

	if label is None:
		raise Unhandled("a match expression whose label does not end its line")

	end = indent + "end " + label.group(0).rstrip("\r")
	close = next((j for j in range(line_number, len(lines)) if lines[j].rstrip("\r") == end), None)

	if close is None:
		raise Unhandled(f"the match {label.group(0)} has no `end {label.group(0)}`")

	for j in range(line_number, close):
		arm = lines[j]

		if not arm.startswith(indent + "\t") or arm.startswith(indent + "\t\t"):
			continue

		at = arm.find(ARM_SEPARATOR)

		if at < 0 or "//" in arm:
			raise Unhandled(f"the match arm `{arm.strip()}` is not a one-line `pattern gives value`")

		start = at + len(ARM_SEPARATOR)
		stop = len(arm.rstrip("\r"))
		lines[j] = cast(arm, start, stop, target)


def fix_line(line, column, code, message, parents, ranges):
	at = column - 1
	m = BINARY.match(message)

	if code == "E3005" and m:
		op = m.group("op")
		range_keyword = next((k for k in RANGE_KEYWORDS if line.startswith(k, at)), None)

		left, right = m.group("left"), m.group("right")

		if range_keyword is not None:
			require_castable(parents, ranges, right, left)
			start, end = binary_operand_after(line, at + len(range_keyword), op)
			return cast(line, start, end, left)

		if not line.startswith(op, at):
			raise Unhandled(f"operator '{op}' is not at the reported column")

		right_span = find_operand(binary_operand_after, line, at + len(op), op)
		left_span = find_operand(binary_operand_before, line, at, op)

		if NUMBER_LITERAL.fullmatch(operand_text(line, right_span)):
			require_castable(parents, ranges, left, right)
			return cast(line, *require_operand(left_span), right)

		if NUMBER_LITERAL.fullmatch(operand_text(line, left_span)):
			require_castable(parents, ranges, right, left)
			return cast(line, *require_operand(right_span), left)

		target = common_ancestor(parents, left, right)

		if right != target:
			line = cast(line, *require_operand(right_span), target)

		if left != target:
			line = cast(line, *require_operand(left_span), target)

		return line

	m = MISMATCH.match(message)

	if code == "E3005" and m:
		require_widening(parents, m.group("got"), m.group("expected"))

		if at < len(line) and line[at] in ",)]}":
			start, end = atom_before(line, at)
		else:
			start, end = atom_after(line, at)

		return cast(line, start, end, m.group("expected"))

	m = TERNARY.match(message)

	if code == "E2028" and m:
		if not line.startswith("if ", at):
			raise Unhandled("a ternary's `if` is not at the reported column")

		when_true, when_false = m.group("whenTrue"), m.group("whenFalse")
		target = common_ancestor(parents, when_true, when_false)
		else_at = line.index(" else ", at)

		if when_false != target:
			start, end = atom_after(line, else_at + len(" else "))
			line = cast(line, start, end, target)

		if when_true != target:
			start, end = atom_before(line, at)
			line = cast(line, start, end, target)

		return line

	m = FIELD.match(message)

	if code == "E3005" and m:
		require_widening(parents, m.group("got"), m.group("expected"))
		field = m.group("field")

		if not line.startswith(field, at):
			raise Unhandled(f"field '{field}' is not at the reported column")

		after = line[at + len(field):]
		separator = re.match(r"\s*(:|=)\s*", after)

		if separator is None:
			raise Unhandled(f"field '{field}' is followed by neither `:` nor `=`")

		start, end = statement_value(line, at + len(field) + separator.end())
		return cast(line, start, end, m.group("expected"))

	m = OTHERWISE.match(message)

	if code == "E3059" and m:
		require_widening(parents, m.group("got"), m.group("expected"))
		keyword = line.find(OTHERWISE_KEYWORD, at)

		if keyword < 0:
			raise Unhandled("no `otherwise` after the reported column")

		start, end = statement_value(line, keyword + len(OTHERWISE_KEYWORD))
		return line[:end] + f" as {m.group('expected')}" + line[end:]

	m = UNUSED_EXPORT.match(message)

	if code == "E3092" and m:
		declaration = re.match(r"^(\s*)export ", line)

		if declaration is None or not line.startswith(m.group("name"), at):
			raise Unhandled("no `export` declaration of that name at the reported column")

		return declaration.group(1) + line[declaration.end():]

	m = ARGUMENT.match(message)

	if code == "E3005" and m:
		require_widening(parents, m.group("got"), m.group("expected"))
		start, end = argument_span(line, at, m.group("label"))
		return cast(line, start, end, m.group("expected"))

	if code == "E3057" and DIVISION_WITHOUT_TRY.match(message):
		op = next((o for o in DIVISION_OPERATORS if line.startswith(o, at)), None)

		if op is None:
			raise Unhandled("no division operator at the reported column")

		start, _ = binary_operand_before(line, at, op)
		_, end = binary_operand_after(line, at + len(op), op)
		preceding = line[:start].rstrip()

		if any(preceding.endswith(p) for p in MULTIPLICATIVE_OPERATORS) or preceding.endswith("-"):
			raise Unhandled(f"the dividend is the right operand of a tighter or equal-binding operator, so `{op}` does not head its own expression")

		return line[:start] + f"(try ({line[start:end]}) otherwise panic(\"{DIVISOR_NEVER_ZERO}\"))" + line[end:]

	if code == "E3010" and UNNEEDED_CAST.match(message):
		cast_at = CAST_SUFFIX.match(line, at - 1)

		if cast_at is None or not line.startswith("as ", at):
			raise Unhandled("no cast at the reported column")

		return line[:cast_at.start()] + line[cast_at.end():]

	m = IMMUTABLE_TO_MUTABLE.match(message)

	if code == "E3078" and m:
		assignment = re.compile(r"\b" + re.escape(m.group("target")) + r"\s*=\s*" + re.escape(m.group("source")) + r"\b(?![.(])").search(line, at)

		if assignment is None:
			raise Unhandled(f"no `{m.group('target')} = {m.group('source')}` at the reported column")

		return line[:assignment.end()] + CLONE_CALL + line[assignment.end():]

	raise Unhandled("a refusal this script does not cast")


class MemberDeclarations:
	def __init__(self, work):
		self.sites = {}

		for path in maxon_sources(work, SOURCE_DIRS):
			rel = os.path.relpath(path, work).replace("\\", "/")
			enclosing = None

			for line in read(path).split("\n"):
				top = TOP_LEVEL_DECLARATION.match(line)

				if top:
					enclosing = (top.group("keyword"), top.group("name"))

				member = MEMBER_DECLARATION.match(line)

				if member:
					self.sites.setdefault(member.group("name"), set()).add((rel, enclosing))

	def proves_read_only(self, method):
		if method not in READ_ONLY_COLLECTION_METHODS:
			return False

		sites = self.sites.get(method)

		if not sites:
			return False

		return all(is_collection_member(rel, enclosing) for rel, enclosing in sites)


def is_collection_member(rel, enclosing):
	if enclosing is None:
		return False

	keyword, name = enclosing
	return keyword in ("type", "extension") and name in COLLECTION_TYPES and rel == f"{STDLIB_DIR}/{name}.maxon"


def require_read_only_via(borrow, iterated, members):
	owner, via = borrow.group("owner"), borrow.group("via")

	if members.proves_read_only(via):
		return

	if any(owner in segments for segments in chain_segments(iterated)):
		where = f"`{owner}`, which the loop iterates through"
	else:
		where = f"`{owner}`, which this script cannot place on the iterated `{iterated}`"

	raise Unhandled(f"the refused mutation reaches {where}, via `{via}`, which is not a read-only {'/'.join(sorted(COLLECTION_TYPES))} method of {STDLIB_DIR}/, so this script cannot prove it leaves the iterated collection unmutated and iterating a clone of it could change what the loop sees")


def hoist_loop_borrow(lines, line_number, borrow, members, rel):
	borrow_index = int(borrow.group("line")) - 1

	if not borrow_index < line_number - 1:
		raise Unhandled("the borrow does not precede the refused mutation")

	loop = FOR_LOOP.match(lines[borrow_index])

	if loop is None or loop.group("element") != borrow.group("element"):
		raise Unhandled(f"no `for {borrow.group('element')} in ...` loop at line {borrow.group('line')}")

	iterated = loop.group("iterated")

	if re.fullmatch(r"[A-Za-z0-9_]+", iterated) or " upto " in iterated or " downto " in iterated:
		raise Unhandled("the loop does not iterate a borrowed collection")

	element = loop.group("element")
	indent = loop.group("indent")
	label = loop.group("label")

	if is_member_chain(iterated) and iterated.endswith(CLONE_CALL):
		snapshot = iterated
	else:
		proven = PROVEN_LOOP_HOISTS.get((rel, label, iterated, borrow.group("owner"), borrow.group("via")))
		close = loop_end(lines, borrow_index, indent, label)
		regions = CodeRegions(lines)

		if proven is None:
			require_read_only_via(borrow, iterated, members)
			body = [(lines[i], regions.view(i, lines[i])) for i in range(borrow_index + 1, close)]
			require_unmutated(body, collection_spellings(iterated), members)
		else:
			digest = loop_digest(lines, regions, borrow_index, close)

			if digest != proven:
				raise Unhandled(f"the loop {label} in {rel} is a proven hoist only while its text digests to {proven}, and it now digests to {digest}; prove again that nothing its body reaches mutates `{iterated}`, then record the new digest in PROVEN_LOOP_HOISTS")

		snapshot = f"({iterated}){CLONE_CALL}"

	held = HELD_PREFIX + element[0].upper() + element[1:]
	eol = loop.group("eol")
	lines[borrow_index] = f"{indent}for {element} in {held} {label}{eol}"
	lines.insert(borrow_index, f"{indent}let {held} = {snapshot}{eol}")


def loop_digest(lines, regions, loop_index, close):
	normalized = (" ".join(regions.uncommented(i, lines[i]).split()) for i in range(loop_index, close + 1))
	return hashlib.sha256("\n".join(line for line in normalized if line).encode("utf-8")).hexdigest()


def is_member_chain(expression):
	try:
		begin, end = atom_after(expression, 0)
	except Unhandled:
		return False

	return begin == 0 and end == len(expression)


def loop_end(lines, loop_index, indent, label):
	end = re.compile(r"^" + re.escape(indent) + r"end " + re.escape(label) + r"\r?$")
	close = next((j for j in range(loop_index + 1, len(lines)) if end.match(lines[j])), None)

	if close is None:
		raise Unhandled(f"the loop {label} has no `end {label}`")

	return close


def chain_segments(iterated):
	chains = [MEMBER_CHAIN.match(iterated)] if is_member_chain(iterated) else MEMBER_CHAIN.finditer(iterated)

	for m in chains:
		if m is None:
			continue

		segments = m.group(0).split(".")

		if m.end() < len(iterated) and iterated[m.end()] == "(":
			segments = segments[:-1]

		yield segments


def collection_spellings(iterated):
	spellings = {iterated}

	for segments in chain_segments(iterated):
		for count in range(1, len(segments) + 1):
			prefix = ".".join(segments[:count])

			if prefix not in KEYWORDS:
				spellings.add(prefix)

	return spellings


def require_unmutated(body, spellings, members):
	for line, code in body:
		for spelling in sorted(spellings, key=len, reverse=True):
			for m in re.finditer(re.escape(spelling), code):
				reason = mutation_at(code, m.start(), m.end(), members)

				if reason is not None:
					raise Unhandled(f"the loop body {reason.format(f'`{spelling}`')}, which the loop iterates, so iterating a clone of it could change what the loop sees: {line.strip()}")


def mutation_at(code, start, end, members):
	if start > 0 and (IDENT.match(code[start - 1]) or code[start - 1] == "."):
		return None

	if end < len(code) and IDENT.match(code[end]):
		return None

	i = end
	calls = False

	while i < len(code):
		if code[i] == "[":
			i = match_forward(code, i) + 1
		elif code[i] == "." and i + 1 < len(code) and IDENT.match(code[i + 1]):
			j = i + 1

			while j < len(code) and IDENT.match(code[j]):
				j += 1

			if j < len(code) and code[j] == "(":
				if not members.proves_read_only(code[i + 1:j]):
					return f"calls `{code[i + 1:j]}` on {{}}, which this script cannot prove leaves it unmutated"

				calls = True
				j = match_forward(code, j) + 1

			i = j
		else:
			break

	if ASSIGNMENT.match(code, i):
		return "assigns to or through {}"

	if calls:
		return None

	before = code[:start].rstrip()
	labelled = re.search(r"[A-Za-z_][A-Za-z0-9_]*:$", before)

	if labelled:
		before = before[:labelled.start()].rstrip()

	after = code[i:].lstrip()

	if before.endswith(("(", ",")) and after.startswith((")", ",")):
		return "passes {} to a call"

	assigned = re.search(r"(?:^|[^=!<>+\-*/%])=$", before)

	if assigned and not re.match(r"\s*let\b", code) and (after == "" or after.startswith("'")):
		return "binds a mutable alias to {}"

	return None


def argument_span(line, at, label):
	i = at

	while i < len(line) and (IDENT.match(line[i]) or line[i] == "."):
		i += 1

	if i >= len(line) or line[i] != "(":
		raise Unhandled("no call at the reported column")

	close = match_forward(line, i)
	arguments = []
	begin = i + 1
	depth = 0
	j = begin

	while j < close:
		c = line[j]

		if c == '"':
			j = line.index('"', j + 1)
		elif c in OPENERS:
			depth += 1
		elif c in CLOSERS:
			depth -= 1
		elif c == "," and depth == 0:
			arguments.append((begin, j))
			begin = j + 1

		j += 1

	arguments.append((begin, close))
	spans = []

	for a, b in arguments:
		while a < b and line[a] == " ":
			a += 1

		labelled = re.match(r"([A-Za-z0-9_]+):\s*", line[a:b])

		if labelled and labelled.group(1) == label:
			return a + labelled.end(), b

		spans.append((a, b, labelled is not None))

	if spans and not spans[0][2]:
		return spans[0][0], spans[0][1]

	raise Unhandled(f"no argument for '{label}' in the call")


def build(work, seed_name):
	result = run([os.path.join(work, ".bootstrap", seed_name), "build", "maxon-bin", "--output=out/c1" + os.path.splitext(seed_name)[1]], cwd=work, check=False)
	return result.returncode, result.stdout + result.stderr


def resolve(work, path):
	path = path.replace("\\", "/")

	if not os.path.isabs(path):
		path = os.path.join(work, path)

	rel = os.path.relpath(path, work).replace("\\", "/")

	if rel.startswith(".."):
		raise Unhandled(f"{path} lies outside the tree the seed was given")

	return os.path.join(work, rel), rel


def report_refusals(what, refused, work):
	print(f"generate-seed-language-shim.py: {what}:", file=sys.stderr)
	print("\n".join(refused), file=sys.stderr)
	print(f"work tree: {work}", file=sys.stderr)
	return 1


def main():
	here = os.path.dirname(os.path.abspath(__file__))
	parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
	parser.add_argument("--tree", default=os.path.dirname(os.path.dirname(here)))
	parser.add_argument("--seed")
	parser.add_argument("--work")
	parser.add_argument("--output")
	parser.add_argument("--resume", action="store_true")
	args = parser.parse_args()

	tree = os.path.abspath(args.tree)
	seed = args.seed or os.path.join(tree, ".bootstrap", "maxon.exe" if os.name == "nt" else "maxon")
	output = os.path.abspath(args.output or os.path.join(tree, "scripts", "seed-shim", PATCH_NAME))
	work = os.path.abspath(args.work or tempfile.mkdtemp(prefix="seed-language-shim-"))

	if not os.path.isfile(seed):
		raise SystemExit(f"generate-seed-language-shim.py: no seed at {seed} - run scripts/fetch-seed.sh")

	if args.resume != (os.path.exists(work) and bool(os.listdir(work))):
		raise SystemExit(f"generate-seed-language-shim.py: {work} must be {'a work directory a previous run left' if args.resume else 'empty'}")

	parents, ranges = collect_aliases(tree)

	if not args.resume:
		os.makedirs(work, exist_ok=True)
		stage_work(tree, work, seed, output)
		generics = strip_generic_functions(work)
		print(f"withdrew {generics} generic functions", flush=True)
		print(f"stripped {strip_clauses(work)} implements clauses", flush=True)
		widened, refused = write_wide_literals_in_hex(work)

		if refused:
			return report_refusals("an integer literal this script cannot write in a form the seed lexes", refused, work)

		print(f"wrote {widened} integer literals past the seed's decimal range in hex", flush=True)
		unqualified, refused = strip_namespace_qualifiers(work)

		if refused:
			return report_refusals("a qualifier this script cannot write bare without changing the declaration it names", refused, work)

		print(f"unqualified {unqualified} lines naming a `{NAMESPACE_QUALIFIER}` declaration", flush=True)

		annotated, refused = annotate_inferred_fields(work)

		if refused:
			return report_refusals("a field default whose type this script cannot write back as an annotation", refused, work)

		print(f"annotated {annotated} inferred fields", flush=True)

	members = MemberDeclarations(work)
	casts = 0
	seen = set()
	attempts = {}

	for round_number in range(1, MAX_ROUNDS + 1):
		code, log = build(work, os.path.basename(seed))

		with open(os.path.join(work, f"round-{round_number:03}.log"), "w", encoding="utf-8") as f:
			f.write(log)

		if code == 0:
			print(f"round {round_number}: the seed builds the shimmed tree ({casts} casts)", flush=True)
			break

		diagnostics = [m for m in map(DIAGNOSTIC.match, log.splitlines()) if m]

		if not diagnostics:
			raise SystemExit(f"generate-seed-language-shim.py: the seed exited {code} with no diagnostic\n{log}")

		by_file = {}
		refused = []

		for d in diagnostics:
			try:
				path, rel = resolve(work, d.group("path"))
			except Unhandled as e:
				refused.append(f"{d.group(0)}\n    {e}")
				continue

			by_file.setdefault(path, []).append((int(d.group("line")), int(d.group("column")), d, rel))

		for path, sites in by_file.items():
			lines = read(path).split("\n")
			hoists = []

			for line_number, column, d, rel in sorted(sites, key=lambda s: (s[0], s[1]), reverse=True):
				key = (rel, line_number, lines[line_number - 1], d.group("message"))

				site = (rel, line_number, d.group("message"))
				attempts[site] = attempts.get(site, 0) + 1

				if key in seen or attempts[site] > MAX_ATTEMPTS_PER_SITE:
					refused.append(f"{d.group(0)}\n    the cast written for it did not answer it")
					continue

				seen.add(key)

				borrow = BORROWED_BY_LOOP.match(d.group("message"))

				if d.group("code") == "E3070" and borrow:
					hoists.append((int(borrow.group("line")), line_number, borrow, d, rel))
					continue

				try:
					if d.group("code") == "E3005" and MATCH_ARMS.match(d.group("message")):
						cast_match_arms(lines, line_number, d.group("message"), parents)
					else:
						lines[line_number - 1] = fix_line(lines[line_number - 1], column, d.group("code"), d.group("message"), parents, ranges)

					casts += 1
				except Unhandled as e:
					refused.append(f"{d.group(0)}\n    {e}")

			hoisted = set()

			for borrow_line, line_number, borrow, d, rel in sorted(hoists, key=lambda s: s[0], reverse=True):
				if borrow_line in hoisted:
					continue

				try:
					hoist_loop_borrow(lines, line_number, borrow, members, rel)
					hoisted.add(borrow_line)
					casts += 1
				except Unhandled as e:
					refused.append(f"{d.group(0)}\n    {e}")

			write(path, "\n".join(lines))

		if refused:
			return report_refusals("the seed refused the shimmed tree with what this script does not cast", refused, work)

		print(f"round {round_number}: {len(diagnostics)} refusals cast", flush=True)
	else:
		raise SystemExit(f"generate-seed-language-shim.py: the seed still refuses the tree after {MAX_ROUNDS} rounds")

	diff = git(work, "diff", "--no-color", "--", *SOURCE_DIRS).stdout

	with open(output, "w", encoding="utf-8", newline="\n") as f:
		f.write(HEADER)
		f.write(diff)

	print(f"wrote {output}", flush=True)
	return 0


if __name__ == "__main__":
	sys.exit(main())
