#!/usr/bin/env python3
"""generate-seed-language-shim.py - write the seed shim that withdraws every language form the seed cannot parse.

Two forms: a `typealias ... implements` clause and a generic function (`function f(...) uses T`). The seed
enforces every ranged typealias nominally, so once the clauses are gone each widening crossing the tree
relies on is an E3005/E2028 there; a generic function is withdrawn whole, which the tree affords because
the compiler calls none. This script copies the tree's `maxon-bin/`, `stdlib/` and `runtime/` into a
scratch directory, stages every other patch in `scripts/seed-shim/` in sorted order, strips both forms, and
then builds with the seed until it is clean, writing at every site the seed refuses the cast to the parent
it names. The difference is the patch.

Usage:
  python scripts/seed-shim/generate-seed-language-shim.py [--tree DIR] [--seed PATH] [--work DIR] [--output PATH]

Exit codes: 0 the patch was written; 1 the seed refused the tree with something this script does not cast.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

PATCH_NAME = "0016-withdraw-the-language-forms-the-seed-cannot-parse-from-the-first-build.patch"
SOURCE_DIRS = ["maxon-bin", "stdlib", "runtime"]
MAX_ROUNDS = 500

HEADER = """# The seed cannot parse a generic function, so each is withdrawn whole; the compiler calls none of them.
# The seed cannot parse a `typealias X = int(range) implements Parent` clause either, and it enforces every ranged
# typealias nominally at every crossing. Each clause is withdrawn, and every place the tree widens a subtype
# to its parent without a cast gets the cast the seed names. The declarations, their ranges and every table
# stay, so `C1` knows the clause and compiles the unshimmed tree into `C2`. An `export` whose only reach beyond
# its file was through such a crossing is an E3092 to the seed once the crossing is a cast, so it is withdrawn too.
# GENERATED by `scripts/seed-shim/generate-seed-language-shim.py`; regenerate it when the sources it touches move.
"""

DECLARATION = re.compile(r"^(?P<head>(?:[a-z]+ )*typealias (?P<name>[A-Za-z0-9_]+) = [^\r\n]*?) implements (?P<parent>[A-Za-z0-9_]+)[ \t]*(?P<eol>\r?)$", re.M)
GENERIC_FUNCTION = re.compile(r"^(?P<indent>[ \t]*)(?:[a-z]+ )*function (?P<name>[A-Za-z0-9_]+)\(.*\) uses [A-Z][^\r\n]*$")
DIAGNOSTIC = re.compile(r"^error (?P<code>E\d+): (?P<path>.+?):(?P<line>\d+):(?P<column>\d+): (?P<message>.*)$")
BINARY = re.compile(r"^operator '(?P<op>[^']+)' requires both operands to be the same type: '(?P<left>[A-Za-z0-9_]+)' and '(?P<right>[A-Za-z0-9_]+)' are different typealiases")
MISMATCH = re.compile(r"^type mismatch: 'expected (?P<expected>[A-Za-z0-9_]+), got (?P<got>[A-Za-z0-9_]+)'")
TERNARY = re.compile(r"^ternary expression type mismatch: true branch is '(?P<whenTrue>[A-Za-z0-9_]+)' but false branch is '(?P<whenFalse>[A-Za-z0-9_]+)'")
UNUSED_EXPORT = re.compile(r"^exported [a-z]+ '(?P<name>[A-Za-z0-9_]+)' is never referenced outside its declaring file")
ARGUMENT = re.compile(r"^argument type mismatch for '(?P<label>[A-Za-z0-9_]+)': expected '(?P<expected>[A-Za-z0-9_]+)', got '(?P<got>[A-Za-z0-9_]+)'")
FIELD = re.compile(r"^cannot assign a value of type '(?P<got>[A-Za-z0-9_]+)' to (?:field|variable) '(?P<field>[A-Za-z0-9_]+)'(?: of '[A-Za-z0-9_]+')?, which holds '(?P<expected>[A-Za-z0-9_]+)'")

KEYWORDS = {"if", "else", "while", "return", "not", "and", "or", "then", "gives", "let", "var", "for", "in", "upto", "downto", "match", "try", "otherwise", "throw", "as"}
IDENT = re.compile(r"[A-Za-z0-9_]")
OPENERS = {"(": ")", "[": "]", "{": "}"}
CLOSERS = {v: k for k, v in OPENERS.items()}
ARITHMETIC = ["+", "-", "*", "/", "%"]
COMPARISON = {"==", "!=", "<", "<=", ">", ">="}


class Unhandled(Exception):
	pass


def run(args, cwd, check=True):
	result = subprocess.run(args, cwd=cwd, capture_output=True, text=True, encoding="utf-8", errors="replace")

	if check and result.returncode != 0:
		raise SystemExit(f"generate-seed-language-shim.py: {' '.join(args)} exited {result.returncode}\n{result.stdout}{result.stderr}")

	return result


def git(work, *args):
	return run(["git", "-c", "core.autocrlf=false", "-c", "user.name=shim", "-c", "user.email=shim@localhost", *args], cwd=work)


def stage_work(tree, work, seed, output):
	listed = run(["git", "ls-files", "-co", "--exclude-standard", "-z", "--", *SOURCE_DIRS], cwd=tree).stdout.split("\0")

	for rel in filter(None, listed):
		src = os.path.join(tree, rel)

		if not os.path.isfile(src):
			continue

		dst = os.path.join(work, rel)
		os.makedirs(os.path.dirname(dst), exist_ok=True)
		shutil.copyfile(src, dst)

	os.makedirs(os.path.join(work, ".bootstrap"), exist_ok=True)
	shutil.copy2(seed, os.path.join(work, ".bootstrap", os.path.basename(seed)))

	git(work, "init", "-q")

	with open(os.path.join(work, ".git", "info", "exclude"), "a", encoding="utf-8") as exclude:
		exclude.write("/.bootstrap/\n/maxon-bin/.maxon/\n/out/\n")

	shim_dir = os.path.join(tree, "scripts", "seed-shim")
	patches = sorted(p for p in os.listdir(shim_dir) if p.endswith(".patch"))

	for patch in patches:
		path = os.path.join(shim_dir, patch)

		if os.path.abspath(path) == os.path.abspath(output):
			continue

		git(work, "apply", "--", path)

	git(work, "add", "-A")
	git(work, "commit", "-q", "-m", "base")


def strip_clauses(work):
	parents = {}

	for directory in SOURCE_DIRS:
		for dirpath, _, files in os.walk(os.path.join(work, directory)):
			for name in files:
				if not name.endswith(".maxon"):
					continue

				path = os.path.join(dirpath, name)
				text = read(path)

				if " implements " not in text:
					continue

				for m in DECLARATION.finditer(text):
					parents[m.group("name")] = m.group("parent")

				stripped = DECLARATION.sub(lambda m: m.group("head") + m.group("eol"), text)

				if stripped != text:
					write(path, stripped)

	return parents


def strip_generic_functions(work):
	withdrawn = 0

	for directory in SOURCE_DIRS:
		for dirpath, _, files in os.walk(os.path.join(work, directory)):
			for name in files:
				if not name.endswith(".maxon"):
					continue

				path = os.path.join(dirpath, name)
				lines = read(path).split("\n")
				kept = []
				i = 0
				changed = False

				while i < len(lines):
					m = GENERIC_FUNCTION.match(lines[i])

					if m is None:
						kept.append(lines[i])
						i += 1
						continue

					end = re.compile(r"^" + re.escape(m.group("indent")) + r"end '" + re.escape(m.group("name")) + r"'\r?$")
					close = next((j for j in range(i + 1, len(lines)) if end.match(lines[j])), None)

					if close is None:
						raise SystemExit(f"generate-seed-language-shim.py: {path}:{i + 1}: generic function '{m.group('name')}' has no `end '{m.group('name')}'`")

					while kept and kept[-1].lstrip().startswith("//"):
						kept.pop()

					i = close + 1

					if i < len(lines) and lines[i].strip() == "":
						i += 1

					withdrawn += 1
					changed = True

				if changed:
					write(path, "\n".join(kept))

	return withdrawn


def read(path):
	with open(path, "r", encoding="utf-8", newline="") as f:
		return f.read()


def write(path, text):
	with open(path, "w", encoding="utf-8", newline="") as f:
		f.write(text)


def ancestors(parents, name):
	chain = [name]

	while chain[-1] in parents:
		chain.append(parents[chain[-1]])

	return chain


def common_ancestor(parents, left, right):
	right_chain = ancestors(parents, right)

	for candidate in ancestors(parents, left):
		if candidate in right_chain:
			return candidate

	raise Unhandled(f"'{left}' and '{right}' share no ancestor through an `implements` clause")


def require_widening(parents, got, expected):
	if expected not in ancestors(parents, got)[1:]:
		raise Unhandled(f"'{got}' does not implement '{expected}', so no widening cast answers this")


def match_back(line, close_index):
	depth = 0
	closer = line[close_index]
	opener = CLOSERS[closer]

	for i in range(close_index, -1, -1):
		if line[i] in "\"'":
			raise Unhandled("a string literal inside the operand")

		if line[i] == closer:
			depth += 1
		elif line[i] == opener:
			depth -= 1

			if depth == 0:
				return i

	raise Unhandled("unbalanced brackets before the operator")


def match_forward(line, open_index):
	depth = 0
	opener = line[open_index]
	closer = OPENERS[opener]
	i = open_index

	while i < len(line):
		c = line[i]

		if c == '"':
			i = line.index('"', i + 1)
		elif c == opener:
			depth += 1
		elif c == closer:
			depth -= 1

			if depth == 0:
				return i

		i += 1

	raise Unhandled("unbalanced brackets after the operator")


def atom_before(line, end):
	i = end

	while i > 0 and line[i - 1] == " ":
		i -= 1

	stop = i

	while i > 0:
		if line[i - 1] in CLOSERS:
			i = match_back(line, i - 1)

		j = i

		while j > 0 and IDENT.match(line[j - 1]):
			j -= 1

		if line[j:i] not in KEYWORDS:
			i = j

		if i > 0 and line[i - 1] == "." and i < stop:
			i -= 1
			continue

		break

	if i == stop:
		raise Unhandled("no operand before the operator")

	return i, stop


def atom_after(line, start):
	i = start

	while i < len(line) and line[i] == " ":
		i += 1

	begin = i

	if i < len(line) and line[i] == "-":
		i += 1

	if i < len(line) and line[i] in OPENERS:
		i = match_forward(line, i) + 1
	else:
		j = i

		while j < len(line) and IDENT.match(line[j]):
			j += 1

		if j == i or line[i:j] in KEYWORDS:
			raise Unhandled("no operand after the operator")

		i = j

	while i < len(line):
		if line[i] in "([{":
			i = match_forward(line, i) + 1
		elif line[i] == "." and i + 1 < len(line) and IDENT.match(line[i + 1]):
			i += 1

			while i < len(line) and IDENT.match(line[i]):
				i += 1
		else:
			break

	return begin, i


def binary_operand_before(line, end, op):
	start, stop = atom_before(line, end)

	if op not in COMPARISON:
		return start, stop

	while True:
		i = start

		while i > 0 and line[i - 1] == " ":
			i -= 1

		prior = next((a for a in ARITHMETIC if line[:i].endswith(" " + a)), None)

		if prior is None:
			return start, stop

		start, _ = atom_before(line, i - len(prior))


def binary_operand_after(line, start, op):
	begin, end = atom_after(line, start)

	if op not in COMPARISON:
		return begin, end

	while True:
		rest = line[end:]
		following = next((a for a in ARITHMETIC if rest.startswith(" " + a + " ")), None)

		if following is None:
			return begin, end

		_, end = atom_after(line, end + len(following) + 2)


def statement_value(line, start):
	i = start
	depth = 0

	while i < len(line):
		c = line[i]

		if c == '"':
			i = line.index('"', i + 1)
		elif c in OPENERS:
			depth += 1
		elif c in CLOSERS:
			if depth == 0:
				break

			depth -= 1
		elif c == "," and depth == 0:
			break
		elif c == "'" and depth == 0:
			break

		i += 1

	end = i

	while end > start and line[end - 1] in " \r":
		end -= 1

	if end == start:
		raise Unhandled("no value to cast")

	return start, end


def cast(line, start, end, target):
	inner = line[start:end]

	if re.fullmatch(r"\([A-Za-z0-9_.]+\)", inner):
		inner = inner[1:-1]

	return line[:start] + f"({inner} as {target})" + line[end:]


def fix_line(line, column, code, message, parents):
	at = column - 1
	m = BINARY.match(message)

	if code == "E3005" and m:
		op = m.group("op")

		if not line.startswith(op, at):
			raise Unhandled(f"operator '{op}' is not at the reported column")

		left, right = m.group("left"), m.group("right")
		target = common_ancestor(parents, left, right)

		if right != target:
			start, end = binary_operand_after(line, at + len(op), op)
			line = cast(line, start, end, target)

		if left != target:
			start, end = binary_operand_before(line, at, op)
			line = cast(line, start, end, target)

		return line

	m = MISMATCH.match(message)

	if code == "E3005" and m:
		require_widening(parents, m.group("got"), m.group("expected"))

		if at < len(line) and line[at] in ",)]}":
			start, end = atom_before(line, at)
		else:
			start, end = atom_after(line, at)

		return cast(line, start, end, m.group("expected"))

	m = TERNARY.match(message)

	if code == "E2028" and m:
		if not line.startswith("if ", at):
			raise Unhandled("a ternary's `if` is not at the reported column")

		when_true, when_false = m.group("whenTrue"), m.group("whenFalse")
		target = common_ancestor(parents, when_true, when_false)
		else_at = line.index(" else ", at)

		if when_false != target:
			start, end = atom_after(line, else_at + len(" else "))
			line = cast(line, start, end, target)

		if when_true != target:
			start, end = atom_before(line, at)
			line = cast(line, start, end, target)

		return line

	m = FIELD.match(message)

	if code == "E3005" and m:
		require_widening(parents, m.group("got"), m.group("expected"))
		field = m.group("field")

		if not line.startswith(field, at):
			raise Unhandled(f"field '{field}' is not at the reported column")

		after = line[at + len(field):]
		separator = re.match(r"\s*(:|=)\s*", after)

		if separator is None:
			raise Unhandled(f"field '{field}' is followed by neither `:` nor `=`")

		start, end = statement_value(line, at + len(field) + separator.end())
		return cast(line, start, end, m.group("expected"))

	m = UNUSED_EXPORT.match(message)

	if code == "E3092" and m:
		declaration = re.match(r"^(\s*)export ", line)

		if declaration is None or not line.startswith(m.group("name"), at):
			raise Unhandled("no `export` declaration of that name at the reported column")

		return declaration.group(1) + line[declaration.end():]

	m = ARGUMENT.match(message)

	if code == "E3005" and m:
		require_widening(parents, m.group("got"), m.group("expected"))
		start, end = argument_span(line, at, m.group("label"))
		return cast(line, start, end, m.group("expected"))

	raise Unhandled("a refusal this script does not cast")


def argument_span(line, at, label):
	i = at

	while i < len(line) and (IDENT.match(line[i]) or line[i] == "."):
		i += 1

	if i >= len(line) or line[i] != "(":
		raise Unhandled("no call at the reported column")

	close = match_forward(line, i)
	arguments = []
	begin = i + 1
	depth = 0
	j = begin

	while j < close:
		c = line[j]

		if c == '"':
			j = line.index('"', j + 1)
		elif c in OPENERS:
			depth += 1
		elif c in CLOSERS:
			depth -= 1
		elif c == "," and depth == 0:
			arguments.append((begin, j))
			begin = j + 1

		j += 1

	arguments.append((begin, close))
	spans = []

	for a, b in arguments:
		while a < b and line[a] == " ":
			a += 1

		labelled = re.match(r"([A-Za-z0-9_]+):\s*", line[a:b])

		if labelled and labelled.group(1) == label:
			return a + labelled.end(), b

		spans.append((a, b, labelled is not None))

	if spans and not spans[0][2]:
		return spans[0][0], spans[0][1]

	raise Unhandled(f"no argument for '{label}' in the call")


def build(work, seed_name):
	result = run([os.path.join(work, ".bootstrap", seed_name), "build", "maxon-bin", "--output=out/c1" + os.path.splitext(seed_name)[1]], cwd=work, check=False)
	return result.returncode, result.stdout + result.stderr


def resolve(work, path):
	path = path.replace("\\", "/")

	if not os.path.isabs(path):
		path = os.path.join(work, path)

	rel = os.path.relpath(path, work).replace("\\", "/")

	if rel.startswith(".."):
		raise Unhandled(f"{path} lies outside the tree the seed was given")

	return os.path.join(work, rel), rel


def main():
	here = os.path.dirname(os.path.abspath(__file__))
	parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
	parser.add_argument("--tree", default=os.path.dirname(os.path.dirname(here)))
	parser.add_argument("--seed")
	parser.add_argument("--work")
	parser.add_argument("--output")
	args = parser.parse_args()

	tree = os.path.abspath(args.tree)
	seed = args.seed or os.path.join(tree, ".bootstrap", "maxon.exe" if os.name == "nt" else "maxon")
	output = os.path.abspath(args.output or os.path.join(tree, "scripts", "seed-shim", PATCH_NAME))
	work = os.path.abspath(args.work or tempfile.mkdtemp(prefix="seed-language-shim-"))

	if not os.path.isfile(seed):
		raise SystemExit(f"generate-seed-language-shim.py: no seed at {seed} - run scripts/fetch-seed.sh")

	if os.path.exists(work) and os.listdir(work):
		raise SystemExit(f"generate-seed-language-shim.py: {work} is not empty")

	os.makedirs(work, exist_ok=True)
	stage_work(tree, work, seed, output)
	generics = strip_generic_functions(work)
	print(f"withdrew {generics} generic functions", flush=True)
	parents = strip_clauses(work)
	print(f"stripped {len(parents)} implements clauses", flush=True)

	casts = 0
	seen = set()

	for round_number in range(1, MAX_ROUNDS + 1):
		code, log = build(work, os.path.basename(seed))

		with open(os.path.join(work, f"round-{round_number:03}.log"), "w", encoding="utf-8") as f:
			f.write(log)

		if code == 0:
			print(f"round {round_number}: the seed builds the shimmed tree ({casts} casts)", flush=True)
			break

		diagnostics = [m for m in map(DIAGNOSTIC.match, log.splitlines()) if m]

		if not diagnostics:
			raise SystemExit(f"generate-seed-language-shim.py: the seed exited {code} with no diagnostic\n{log}")

		by_file = {}
		refused = []

		for d in diagnostics:
			try:
				path, rel = resolve(work, d.group("path"))
			except Unhandled as e:
				refused.append(f"{d.group(0)}\n    {e}")
				continue

			by_file.setdefault(path, []).append((int(d.group("line")), int(d.group("column")), d, rel))

		for path, sites in by_file.items():
			lines = read(path).split("\n")

			for line_number, column, d, rel in sorted(sites, key=lambda s: (s[0], s[1]), reverse=True):
				key = (rel, line_number, lines[line_number - 1], d.group("message"))

				if key in seen:
					refused.append(f"{d.group(0)}\n    the cast written for it did not answer it")
					continue

				seen.add(key)

				try:
					lines[line_number - 1] = fix_line(lines[line_number - 1], column, d.group("code"), d.group("message"), parents)
					casts += 1
				except Unhandled as e:
					refused.append(f"{d.group(0)}\n    {e}")

			write(path, "\n".join(lines))

		if refused:
			print("generate-seed-language-shim.py: the seed refused the shimmed tree with what this script does not cast:", file=sys.stderr)
			print("\n".join(refused), file=sys.stderr)
			print(f"work tree: {work}", file=sys.stderr)
			return 1

		print(f"round {round_number}: {len(diagnostics)} refusals cast", flush=True)
	else:
		raise SystemExit(f"generate-seed-language-shim.py: the seed still refuses the tree after {MAX_ROUNDS} rounds")

	diff = git(work, "diff", "--no-color", "--", *SOURCE_DIRS).stdout

	with open(output, "w", encoding="utf-8", newline="\n") as f:
		f.write(HEADER)
		f.write(diff)

	print(f"wrote {output}", flush=True)
	return 0


if __name__ == "__main__":
	sys.exit(main())
