/**
 * X86 Disassembler Implementation
 *
 * Uses Zydis to convert x86-64 machine code to Intel syntax assembly.
 */

#include "x86_disassembler.h"
#include <Zydis/Zydis.h>
#include <sstream>

namespace backend {

X86Disassembler::X86Disassembler() {
	decoder = new ZydisDecoder();
	formatter = new ZydisFormatter();

	ZydisDecoderInit(static_cast<ZydisDecoder *>(decoder), ZYDIS_MACHINE_MODE_LONG_64,
					 ZYDIS_STACK_WIDTH_64);

	ZydisFormatterInit(static_cast<ZydisFormatter *>(formatter), ZYDIS_FORMATTER_STYLE_INTEL);

	// Customize formatter for cleaner output
	ZydisFormatterSetProperty(static_cast<ZydisFormatter *>(formatter),
							  ZYDIS_FORMATTER_PROP_FORCE_SIZE, ZYAN_FALSE);
	ZydisFormatterSetProperty(static_cast<ZydisFormatter *>(formatter),
							  ZYDIS_FORMATTER_PROP_HEX_UPPERCASE, ZYAN_FALSE);
}

X86Disassembler::~X86Disassembler() {
	delete static_cast<ZydisDecoder *>(decoder);
	delete static_cast<ZydisFormatter *>(formatter);
}

std::string X86Disassembler::disassemble(const std::vector<uint8_t> &code, uint64_t baseAddress) {
	std::ostringstream ss;

	ZydisDecodedInstruction instruction;
	ZydisDecodedOperand operands[ZYDIS_MAX_OPERAND_COUNT];

	size_t offset = 0;
	while (offset < code.size()) {
		if (ZYAN_SUCCESS(ZydisDecoderDecodeFull(static_cast<ZydisDecoder *>(decoder),
												code.data() + offset, code.size() - offset,
												&instruction, operands))) {
			char buffer[256];
			ZydisFormatterFormatInstruction(static_cast<ZydisFormatter *>(formatter), &instruction,
											operands, instruction.operand_count_visible, buffer,
											sizeof(buffer), baseAddress + offset, ZYAN_NULL);

			ss << "  " << buffer << "\n";
			offset += instruction.length;
		} else {
			// Invalid instruction - emit as data byte
			ss << "  db 0x" << std::hex << static_cast<int>(code[offset]) << std::dec << "\n";
			offset++;
		}
	}

	return ss.str();
}

std::string
X86Disassembler::disassembleWithSymbols(const std::vector<FunctionCode> &functions,
										const std::unordered_map<std::string, size_t> &functionOffsets) {
	std::ostringstream ss;

	ss << "; x86-64 Assembly (Intel syntax)\n";
	ss << "; Generated by Maxon Compiler\n\n";

	for (const auto &func : functions) {
		// Skip runtime/stdlib functions for cleaner output
		if (func.name.find("_start") == 0 || func.name.find("__") == 0) {
			continue;
		}

		// Clean up function name for display
		std::string displayName = func.name;

		// Remove namespace prefix if present (e.g., "compiler_explorer.add" -> "add")
		size_t dotPos = displayName.rfind('.');
		if (dotPos != std::string::npos) {
			displayName = displayName.substr(dotPos + 1);
		}

		ss << displayName << ":\n";

		// Get base address for this function (default to 0 if not provided)
		uint64_t baseAddr = 0;
		auto it = functionOffsets.find(func.name);
		if (it != functionOffsets.end()) {
			baseAddr = it->second;
		}

		// Disassemble the function body
		ZydisDecodedInstruction instruction;
		ZydisDecodedOperand operands[ZYDIS_MAX_OPERAND_COUNT];

		size_t offset = 0;
		while (offset < func.code.size()) {
			if (ZYAN_SUCCESS(ZydisDecoderDecodeFull(static_cast<ZydisDecoder *>(decoder),
													func.code.data() + offset,
													func.code.size() - offset, &instruction,
													operands))) {
				char buffer[256];
				ZydisFormatterFormatInstruction(static_cast<ZydisFormatter *>(formatter),
												&instruction, operands,
												instruction.operand_count_visible, buffer,
												sizeof(buffer), baseAddr + offset, ZYAN_NULL);

				ss << "  " << buffer << "\n";
				offset += instruction.length;
			} else {
				// Invalid instruction - emit as data byte
				ss << "  db 0x" << std::hex << static_cast<int>(func.code[offset]) << std::dec
				   << "\n";
				offset++;
			}
		}

		ss << "\n";
	}

	return ss.str();
}

} // namespace backend
