using MaxonSharp.Compiler.Mlir.Dialects;

namespace MaxonSharp.Compiler.Mlir;

public partial class ARM64CodeEmitter {

  // Memory manager header layout — unified with x86, see RuntimeEmitter.cs for constants.
  // [ptr - 32]: total_alloc_size (8 bytes) — used by mm_free for munmap
  // [ptr - 24]: packed: (alloc_id << 16 | tag_index) (8 bytes)
  // [ptr - 16]: destructor_fn_ptr (8 bytes)
  // [ptr -  8]: refcount (8 bytes)
  // [ptr     ]: user data
  // MM function code is generated by RuntimeEmitter (unified for x86 and ARM64).

  public void EmitMemoryManagerFunctions(List<string?>? tagTable) {
    var rt = new Runtime.RuntimeEmitter(CreateBackend());
    rt.EmitMmGlobals(Compiler.MmTrace, Compiler.MmDebug);
    rt.EmitMmAlloc(Compiler.MmTrace, Compiler.MmDebug);
    rt.EmitMmRealloc(Compiler.MmTrace, Compiler.MmDebug);
    rt.EmitMmFree(Compiler.MmTrace, Compiler.MmDebug);
    rt.EmitMmIncref(Compiler.MmTrace);
    rt.EmitMmDecref(Compiler.MmTrace);
    EmitMmDecrefManagedElements();
    EmitMmIncrefManagedElements();
    EmitMmClearManagedElements();
    EmitMmLeakCheck();
    EmitMmValidatePtr();

    // Managed list operations
    EmitManagedListInsertAfter();
    EmitManagedListInsertBefore();
    EmitManagedListUnlink();
    EmitManagedListClear();
    EmitManagedListClearManaged();
    EmitManagedListDecrefValues();

    // Trace functions
    EmitMmTracePrintTag();
    EmitMmTracePrintHex();
    EmitMmTracePrintI64();
    EmitMmTracePrintPackedTag();
    EmitMmTracePrintIndent();
    EmitMmTraceTransfer();
    EmitMmTagLookup(tagTable);
  }

  // --- mm_decref_managed_elements(list_ptr) ---
  private void EmitMmDecrefManagedElements() {
    // Iterate managed list elements and decref each
    // list: [ptr+0]=buf, [ptr+8]=len
    EmitRuntimeFunctionStart("mm_decref_managed_elements", 1, 0x40);
    EmitReloadArg(0);
    // Load buf and len
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 0, 8); // buf
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X0, 8, 8); // len
    // Save buf [x29, #32], len [x29, #40], idx=0 [x29, #48]
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X29, 32, 8);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X29, 40, 8);
    EmitMovRegImm(ARM64Register.X4, 0);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X4, ARM64Register.X29, 48, 8);

    var loopLabel = $"__decref_elems_loop_{_uniqueLabelCounter}";
    var doneLabel = $"__decref_elems_done_{_uniqueLabelCounter}";
    _uniqueLabelCounter++;

    DefineLabel(loopLabel);
    // if idx >= len, done
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X4, ARM64Register.X29, 48, 8);
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X29, 40, 8);
    EmitWord(0xEB00001F | (Reg(ARM64Register.X3) << 16) | (Reg(ARM64Register.X4) << 5)); // CMP X4, X3
    _condBranchFixups.Add((_code.Count, doneLabel));
    EmitWord(0x54000000 | CondCode(ARM64ConditionCode.Hs)); // B.HS done

    // Load element: buf[idx*8] using register offset with LSL #3
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = buf
    // LDR X0, [X2, X4, LSL #3] — barrel shifter computes buf + idx*8
    EmitWord(0xF8647840 | (Reg(ARM64Register.X4) << 16) | (Reg(ARM64Register.X2) << 5) | Reg(ARM64Register.X0));

    // mm_decref(element, scope)
    if (Compiler.MmTrace) EmitAdrpAddFixup(ARM64Register.X1, _symdataAdrpFixups, "__mm_scope_managed_elements");
    else EmitMovRegImm(ARM64Register.X1, 0);
    EmitBranchLink("mm_decref");

    // idx++
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X4, ARM64Register.X29, 48, 8);
    EmitAddSubImm(ARM64Register.X4, ARM64Register.X4, 1, isAdd: true);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X4, ARM64Register.X29, 48, 8);
    EmitBranch(loopLabel);

    DefineLabel(doneLabel);
    EmitRuntimeFunctionEnd();
  }

  // --- mm_incref_managed_elements(managed_ptr) ---
  // Increfs every element pointer in a __ManagedMemory buffer.
  // Layout: [+0]=buf, [+8]=len
  private void EmitMmIncrefManagedElements() {
    EmitRuntimeFunctionStart("mm_incref_managed_elements", 1, 0x40);
    EmitReloadArg(0);
    // Load buf and len
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 0, 8); // buf
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X0, 8, 8); // len
    // Save buf [x29, #32], len [x29, #40], idx=0 [x29, #48]
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X29, 32, 8);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X29, 40, 8);
    EmitMovRegImm(ARM64Register.X4, 0);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X4, ARM64Register.X29, 48, 8);

    var loopLabel = $"__incref_elems_loop_{_uniqueLabelCounter}";
    var doneLabel = $"__incref_elems_done_{_uniqueLabelCounter}";
    var skipLabel = $"__incref_elems_skip_{_uniqueLabelCounter}";
    _uniqueLabelCounter++;

    DefineLabel(loopLabel);
    // if idx >= len, done
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X4, ARM64Register.X29, 48, 8);
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X29, 40, 8);
    EmitWord(0xEB00001F | (Reg(ARM64Register.X3) << 16) | (Reg(ARM64Register.X4) << 5)); // CMP X4, X3
    _condBranchFixups.Add((_code.Count, doneLabel));
    EmitWord(0x54000000 | CondCode(ARM64ConditionCode.Hs)); // B.HS done

    // Load element: buf[idx*8]
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = buf
    EmitWord(0xF8647840 | (Reg(ARM64Register.X4) << 16) | (Reg(ARM64Register.X2) << 5) | Reg(ARM64Register.X0));

    // Null guard: skip null elements
    _condBranchFixups.Add((_code.Count, skipLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X0)); // CBZ X0, skip

    // mm_incref(element, scope=NULL)
    EmitMovRegImm(ARM64Register.X1, 0);
    EmitBranchLink("mm_incref");

    DefineLabel(skipLabel);
    // idx++
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X4, ARM64Register.X29, 48, 8);
    EmitAddSubImm(ARM64Register.X4, ARM64Register.X4, 1, isAdd: true);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X4, ARM64Register.X29, 48, 8);
    EmitBranch(loopLabel);

    DefineLabel(doneLabel);
    EmitRuntimeFunctionEnd();
  }

  // --- mm_clear_managed_elements(managed_ptr) ---
  // Decrefs every element pointer and zeroes each slot.
  // Layout: [+0]=buf, [+8]=len
  private void EmitMmClearManagedElements() {
    EmitRuntimeFunctionStart("mm_clear_managed_elements", 1, 0x40);
    EmitReloadArg(0);
    // Load buf and len
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 0, 8); // buf
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X0, 8, 8); // len
    // Save buf [x29, #32], len [x29, #40], idx=0 [x29, #48]
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X29, 32, 8);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X29, 40, 8);
    EmitMovRegImm(ARM64Register.X4, 0);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X4, ARM64Register.X29, 48, 8);

    var loopLabel = $"__clear_elems_loop_{_uniqueLabelCounter}";
    var doneLabel = $"__clear_elems_done_{_uniqueLabelCounter}";
    var zeroLabel = $"__clear_elems_zero_{_uniqueLabelCounter}";
    _uniqueLabelCounter++;

    DefineLabel(loopLabel);
    // if idx >= len, done
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X4, ARM64Register.X29, 48, 8);
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X29, 40, 8);
    EmitWord(0xEB00001F | (Reg(ARM64Register.X3) << 16) | (Reg(ARM64Register.X4) << 5)); // CMP X4, X3
    _condBranchFixups.Add((_code.Count, doneLabel));
    EmitWord(0x54000000 | CondCode(ARM64ConditionCode.Hs)); // B.HS done

    // Load element: buf[idx*8]
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = buf
    EmitWord(0xF8647840 | (Reg(ARM64Register.X4) << 16) | (Reg(ARM64Register.X2) << 5) | Reg(ARM64Register.X0));

    // Null guard: skip decref for null elements
    _condBranchFixups.Add((_code.Count, zeroLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X0)); // CBZ X0, zero

    // mm_decref(element, scope)
    if (Compiler.MmTrace) EmitAdrpAddFixup(ARM64Register.X1, _symdataAdrpFixups, "__mm_scope_managed_elements");
    else EmitMovRegImm(ARM64Register.X1, 0);
    EmitBranchLink("mm_decref");

    DefineLabel(zeroLabel);
    // Zero the slot: buf[idx*8] = 0
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X4, ARM64Register.X29, 48, 8); // idx
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // buf
    // STR XZR, [X2, X4, LSL #3]
    EmitWord(0xF8247840 | (Reg(ARM64Register.X4) << 16) | (Reg(ARM64Register.X2) << 5) | Reg(ARM64Register.Xzr));

    // idx++
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X4, ARM64Register.X29, 48, 8);
    EmitAddSubImm(ARM64Register.X4, ARM64Register.X4, 1, isAdd: true);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X4, ARM64Register.X29, 48, 8);
    EmitBranch(loopLabel);

    DefineLabel(doneLabel);
    EmitRuntimeFunctionEnd();
  }

  // --- mm_leak_check() ---
  // Checks __mm_alloc_count; if non-zero, prints diagnostic and exits with code 101.
  // Only active when --mm-trace is enabled; otherwise a no-op.
  private void EmitMmLeakCheck() {
    if (!Compiler.MmTrace) {
      DefineLabel("mm_leak_check");
      EmitWord(0xD65F03C0); // RET
      return;
    }

    DefineSymdata("__mm_leak_prefix", "MM leak: \0"u8.ToArray());
    DefineSymdata("__mm_leak_suffix", " allocation(s) remain\n\0"u8.ToArray());

    EmitRuntimeFunctionStart("mm_leak_check", 0, 0x50);

    // Load alloc count
    EmitGlobalLoadReg(ARM64Register.X0, "__mm_alloc_count");
    EmitCbz(ARM64Register.X0, "mm_leak_check_done");

    // Save count at [x29+16]
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X29, 16, 8);

    // Print "MM leak: "
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_leak_prefix");
    EmitBranchLink("rt_write_cstr_stderr");

    // Print count as decimal
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 16, 8);
    EmitBranchLink("mm_trace_print_i64");

    // Print " allocation(s) remain\n"
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_leak_suffix");
    EmitBranchLink("rt_write_cstr_stderr");

    // Leak is fatal when tracing is active
    EmitMovRegImm(ARM64Register.X0, 101);
    EmitCallImport("_exit");

    DefineLabel("mm_leak_check_done");
    EmitRuntimeFunctionEnd();
  }

  // --- mm_validate_ptr(ptr, tag) ---
  // Checks that ptr is non-null and has non-zero refcount. Panics on failure.
  private void EmitMmValidatePtr() {
    DefineSymdata("__mm_validate_tag", "MM VALIDATE ptr=\0"u8.ToArray());
    DefineSymdata("__mm_validate_fail", "VALIDATION FAILED: ptr has zero refcount!\n\0"u8.ToArray());

    EmitRuntimeFunctionStart("mm_validate_ptr", 2, 0x30);
    // [x29+16] = ptr (arg 0), [x29+24] = tag (arg 1)

    EmitReloadArg(0); // X0 = ptr
    // Null is OK — skip validation
    EmitCbz(ARM64Register.X0, "mm_validate_done");

    // Load refcount at [ptr - 8]
    // LDUR X1, [X0, #-8]
    EmitWord(0xF85F8001 | (Reg(ARM64Register.X0) << 5));
    // Non-zero refcount = valid
    EmitCbnz(ARM64Register.X1, "mm_validate_done");

    // FAILED: print "MM VALIDATE ptr=0xHEX\n" then panic
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_validate_tag");
    EmitBranchLink("rt_write_cstr_stderr");

    EmitReloadArg(0); // X0 = ptr
    EmitBranchLink("mm_trace_print_hex");

    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_newline");
    EmitBranchLink("rt_write_cstr_stderr");

    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_validate_fail");
    EmitBranchLink("maxon_panic");

    DefineLabel("mm_validate_done");
    EmitRuntimeFunctionEnd();
  }

  // =========================================================================
  // Managed List operations
  // =========================================================================
  // ManagedListNode layout: [+0]=next, [+8]=prev, [+16]=list, [+24]=value
  // ManagedList layout: [+0]=head, [+8]=tail, [+16]=count

  // --- maxon_managed_list_insert_first(list_ptr, node_ptr) ---
  private void EmitManagedListInsertFirst() {
    // Args: X0=list_ptr [x29,#16], X1=node_ptr [x29,#24]
    EmitRuntimeFunctionStart("maxon_managed_list_insert_first", 2, 0x40);

    // Auto-detach: if node.list != 0, unlink from old list and decref
    EmitReloadArg(1); // X1 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X1, 16, 8); // X2 = node.list
    var noDetachLabel = $"__mli_first_no_detach_{_uniqueLabelCounter++}";
    _condBranchFixups.Add((_code.Count, noDetachLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X2)); // CBZ X2, no_detach
    // Unlink from old list: unlink(old_list, node)
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X2); // X0 = old list
    EmitBranchLink("maxon_managed_list_unlink");
    // Decref node (old list releases reference)
    EmitReloadArg(1); // X0 = node_ptr (reload into X1, move to X0)
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X1);
    EmitMovRegImm(ARM64Register.X1, 0); // scope=NULL
    EmitBranchLink("mm_decref");
    DefineLabel(noDetachLabel);

    // old_head = [list+0]
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 0, 8); // X2 = old_head
    // Save old_head to [x29, #32]
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X29, 32, 8);

    // node.next = old_head
    EmitReloadArg(1); // X1 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X1, 0, 8); // [node+0] = old_head

    // node.prev = 0
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X1, 8, 8); // [node+8] = 0

    // node.list = list_ptr
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X1, 16, 8); // [node+16] = list_ptr

    // if old_head != 0: old_head.prev = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = old_head
    var noOldHeadLabel = $"__mli_first_no_old_head_{_uniqueLabelCounter++}";
    _condBranchFixups.Add((_code.Count, noOldHeadLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X2)); // CBZ X2, no_old_head
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X2, 8, 8); // old_head.prev = node_ptr
    DefineLabel(noOldHeadLabel);

    // list.head = node_ptr
    EmitReloadArg(0); // X0 = list_ptr
    EmitReloadArg(1); // X1 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X0, 0, 8); // [list+0] = node_ptr

    // if list.tail == 0: list.tail = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 8, 8); // X2 = list.tail
    var tailOkLabel = $"__mli_first_tail_ok_{_uniqueLabelCounter++}";
    _condBranchFixups.Add((_code.Count, tailOkLabel));
    EmitWord(0xB5000000 | Reg(ARM64Register.X2)); // CBNZ X2, tail_ok
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X0, 8, 8); // list.tail = node_ptr
    DefineLabel(tailOkLabel);

    // list.count++
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 16, 8); // X2 = count
    EmitAddSubImm(ARM64Register.X2, ARM64Register.X2, 1, isAdd: true);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X0, 16, 8); // [list+16] = count+1

    // Incref node (list holds counted reference)
    EmitReloadArg(1); // X1 = node_ptr
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X1);
    if (Compiler.MmTrace) EmitAdrpAddFixup(ARM64Register.X1, _symdataAdrpFixups, "__mm_scope_list_insert");
    else EmitMovRegImm(ARM64Register.X1, 0);
    EmitBranchLink("mm_incref");

    EmitRuntimeFunctionEnd();
  }

  // --- maxon_managed_list_insert_last(list_ptr, node_ptr) ---
  private void EmitManagedListInsertLast() {
    // Args: X0=list_ptr [x29,#16], X1=node_ptr [x29,#24]
    EmitRuntimeFunctionStart("maxon_managed_list_insert_last", 2, 0x40);

    // Auto-detach
    EmitReloadArg(1); // X1 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X1, 16, 8); // X2 = node.list
    var noDetachLabel = $"__mli_last_no_detach_{_uniqueLabelCounter++}";
    _condBranchFixups.Add((_code.Count, noDetachLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X2)); // CBZ X2, no_detach
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X2);
    EmitBranchLink("maxon_managed_list_unlink");
    EmitReloadArg(1);
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X1);
    EmitMovRegImm(ARM64Register.X1, 0); // scope=NULL
    EmitBranchLink("mm_decref");
    DefineLabel(noDetachLabel);

    // old_tail = [list+8]
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 8, 8); // X2 = old_tail
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X29, 32, 8); // save old_tail

    // node.next = 0
    EmitReloadArg(1); // X1 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X1, 0, 8); // [node+0] = 0

    // node.prev = old_tail
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X1, 8, 8); // [node+8] = old_tail

    // node.list = list_ptr
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X1, 16, 8); // [node+16] = list_ptr

    // if old_tail != 0: old_tail.next = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = old_tail
    var noOldTailLabel = $"__mli_last_no_old_tail_{_uniqueLabelCounter++}";
    _condBranchFixups.Add((_code.Count, noOldTailLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X2)); // CBZ X2, no_old_tail
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X2, 0, 8); // old_tail.next = node_ptr
    DefineLabel(noOldTailLabel);

    // list.tail = node_ptr
    EmitReloadArg(0); // X0 = list_ptr
    EmitReloadArg(1); // X1 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X0, 8, 8); // list.tail = node_ptr

    // if list.head == 0: list.head = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 0, 8); // X2 = list.head
    var headOkLabel = $"__mli_last_head_ok_{_uniqueLabelCounter++}";
    _condBranchFixups.Add((_code.Count, headOkLabel));
    EmitWord(0xB5000000 | Reg(ARM64Register.X2)); // CBNZ X2, head_ok
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X0, 0, 8); // list.head = node_ptr
    DefineLabel(headOkLabel);

    // list.count++
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 16, 8);
    EmitAddSubImm(ARM64Register.X2, ARM64Register.X2, 1, isAdd: true);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X0, 16, 8);

    // Incref node
    EmitReloadArg(1);
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X1);
    if (Compiler.MmTrace) EmitAdrpAddFixup(ARM64Register.X1, _symdataAdrpFixups, "__mm_scope_list_insert");
    else EmitMovRegImm(ARM64Register.X1, 0);
    EmitBranchLink("mm_incref");

    EmitRuntimeFunctionEnd();
  }

  // --- maxon_managed_list_insert_after(list_ptr, target_ptr, node_ptr) ---
  private void EmitManagedListInsertAfter() {
    // Args: X0=list_ptr [x29,#16], X1=target_ptr [x29,#24], X2=node_ptr [x29,#32]
    EmitRuntimeFunctionStart("maxon_managed_list_insert_after", 3, 0x50);

    // Auto-detach
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X2, 16, 8); // X3 = node.list
    var noDetachLabel = $"__mli_after_no_detach_{_uniqueLabelCounter++}";
    _condBranchFixups.Add((_code.Count, noDetachLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X3)); // CBZ X3, no_detach
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X3); // X0 = old list
    EmitMovRegReg(ARM64Register.X1, ARM64Register.X2); // X1 = node
    EmitBranchLink("maxon_managed_list_unlink");
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 32, 8); // X0 = node_ptr
    EmitMovRegImm(ARM64Register.X1, 0); // scope=NULL
    EmitBranchLink("mm_decref");
    DefineLabel(noDetachLabel);

    // after = target.next
    EmitReloadArg(1); // X1 = target_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X1, 0, 8); // X3 = target.next (after)
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X29, 40, 8); // save after

    // node.next = after
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X2, 0, 8); // node.next = after

    // node.prev = target_ptr
    EmitReloadArg(1); // X1 = target_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X2, 8, 8); // node.prev = target

    // node.list = list_ptr
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X2, 16, 8); // node.list = list

    // target.next = node_ptr
    EmitReloadArg(1); // X1 = target_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X1, 0, 8); // target.next = node

    // if after != 0: after.prev = node_ptr; else: list.tail = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X29, 40, 8); // X3 = after
    var wasTailLabel = $"__mli_after_was_tail_{_uniqueLabelCounter}";
    var linkedLabel = $"__mli_after_linked_{_uniqueLabelCounter}";
    _uniqueLabelCounter++;
    _condBranchFixups.Add((_code.Count, wasTailLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X3)); // CBZ X3, was_tail
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X3, 8, 8); // after.prev = node
    EmitBranch(linkedLabel);
    DefineLabel(wasTailLabel);
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X0, 8, 8); // list.tail = node
    DefineLabel(linkedLabel);

    // list.count++
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X0, 16, 8);
    EmitAddSubImm(ARM64Register.X3, ARM64Register.X3, 1, isAdd: true);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X0, 16, 8);

    // Incref node
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 32, 8);
    if (Compiler.MmTrace) EmitAdrpAddFixup(ARM64Register.X1, _symdataAdrpFixups, "__mm_scope_list_insert");
    else EmitMovRegImm(ARM64Register.X1, 0);
    EmitBranchLink("mm_incref");

    EmitRuntimeFunctionEnd();
  }

  // --- maxon_managed_list_insert_before(list_ptr, target_ptr, node_ptr) ---
  private void EmitManagedListInsertBefore() {
    // Args: X0=list_ptr [x29,#16], X1=target_ptr [x29,#24], X2=node_ptr [x29,#32]
    EmitRuntimeFunctionStart("maxon_managed_list_insert_before", 3, 0x50);

    // Auto-detach
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X2, 16, 8); // X3 = node.list
    var noDetachLabel = $"__mli_before_no_detach_{_uniqueLabelCounter++}";
    _condBranchFixups.Add((_code.Count, noDetachLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X3)); // CBZ X3, no_detach
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X3);
    EmitMovRegReg(ARM64Register.X1, ARM64Register.X2);
    EmitBranchLink("maxon_managed_list_unlink");
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 32, 8);
    EmitMovRegImm(ARM64Register.X1, 0); // scope=NULL
    EmitBranchLink("mm_decref");
    DefineLabel(noDetachLabel);

    // before = target.prev
    EmitReloadArg(1); // X1 = target_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X1, 8, 8); // X3 = target.prev (before)
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X29, 40, 8); // save before

    // node.next = target_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = node_ptr
    EmitReloadArg(1); // X1 = target_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X2, 0, 8); // node.next = target

    // node.prev = before
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X29, 40, 8); // X3 = before
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X2, 8, 8); // node.prev = before

    // node.list = list_ptr
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X2, 16, 8); // node.list = list

    // target.prev = node_ptr
    EmitReloadArg(1); // X1 = target_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X1, 8, 8); // target.prev = node

    // if before != 0: before.next = node_ptr; else: list.head = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X29, 40, 8); // X3 = before
    var wasHeadLabel = $"__mli_before_was_head_{_uniqueLabelCounter}";
    var linkedLabel = $"__mli_before_linked_{_uniqueLabelCounter}";
    _uniqueLabelCounter++;
    _condBranchFixups.Add((_code.Count, wasHeadLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X3)); // CBZ X3, was_head
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X3, 0, 8); // before.next = node
    EmitBranch(linkedLabel);
    DefineLabel(wasHeadLabel);
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X0, 0, 8); // list.head = node
    DefineLabel(linkedLabel);

    // list.count++
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X0, 16, 8);
    EmitAddSubImm(ARM64Register.X3, ARM64Register.X3, 1, isAdd: true);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X0, 16, 8);

    // Incref node
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 32, 8);
    if (Compiler.MmTrace) EmitAdrpAddFixup(ARM64Register.X1, _symdataAdrpFixups, "__mm_scope_list_insert");
    else EmitMovRegImm(ARM64Register.X1, 0);
    EmitBranchLink("mm_incref");

    EmitRuntimeFunctionEnd();
  }

  // --- maxon_managed_list_unlink(list_ptr, node_ptr) ---
  private void EmitManagedListUnlink() {
    // Args: X0=list_ptr [x29,#16], X1=node_ptr [x29,#24]
    EmitRuntimeFunctionStart("maxon_managed_list_unlink", 2, 0x40);

    // If node.list == 0, no-op
    EmitReloadArg(1); // X1 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X1, 16, 8); // X2 = node.list
    var doneLabel = $"__mlu_done_{_uniqueLabelCounter++}";
    _condBranchFixups.Add((_code.Count, doneLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X2)); // CBZ X2, done

    // prev = [node+8], next = [node+0]
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X1, 8, 8); // X2 = prev
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X1, 0, 8); // X3 = next
    // Save prev [x29,#32], next [x29,#40]
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X29, 32, 8);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X29, 40, 8);

    // if prev != 0: prev.next = next; else: list.head = next
    var noPrevLabel = $"__mlu_no_prev_{_uniqueLabelCounter}";
    var prevDoneLabel = $"__mlu_prev_done_{_uniqueLabelCounter}";
    _uniqueLabelCounter++;
    _condBranchFixups.Add((_code.Count, noPrevLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X2)); // CBZ X2, no_prev
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X2, 0, 8); // prev.next = next
    EmitBranch(prevDoneLabel);
    DefineLabel(noPrevLabel);
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X3, ARM64Register.X0, 0, 8); // list.head = next
    DefineLabel(prevDoneLabel);

    // if next != 0: next.prev = prev; else: list.tail = prev
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X3, ARM64Register.X29, 40, 8); // X3 = next
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X29, 32, 8); // X2 = prev
    var noNextLabel = $"__mlu_no_next_{_uniqueLabelCounter}";
    var nextDoneLabel = $"__mlu_next_done_{_uniqueLabelCounter}";
    _uniqueLabelCounter++;
    _condBranchFixups.Add((_code.Count, noNextLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X3)); // CBZ X3, no_next
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X3, 8, 8); // next.prev = prev
    EmitBranch(nextDoneLabel);
    DefineLabel(noNextLabel);
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X0, 8, 8); // list.tail = prev
    DefineLabel(nextDoneLabel);

    // Clear node links: next=0, prev=0, list=0
    EmitReloadArg(1); // X1 = node_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X1, 0, 8); // node.next = 0
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X1, 8, 8); // node.prev = 0
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X1, 16, 8); // node.list = 0

    // list.count--
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X2, ARM64Register.X0, 16, 8);
    EmitAddSubImm(ARM64Register.X2, ARM64Register.X2, 1, isAdd: false);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X2, ARM64Register.X0, 16, 8);

    DefineLabel(doneLabel);
    EmitRuntimeFunctionEnd();
  }

  // --- maxon_managed_list_clear(list_ptr) ---
  private void EmitManagedListClear() => EmitManagedListClearImpl("maxon_managed_list_clear", managed: false);

  // --- maxon_managed_list_clear_managed(list_ptr) ---
  private void EmitManagedListClearManaged() => EmitManagedListClearImpl("maxon_managed_list_clear_managed", managed: true);

  // Shared clear implementation
  private void EmitManagedListClearImpl(string funcName, bool managed) {
    // Args: X0=list_ptr [x29,#16]
    // Extra stack: [x29,#24]=current, [x29,#32]=next
    EmitRuntimeFunctionStart(funcName, 1, 0x50);

    // current = list.head
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X1, ARM64Register.X0, 0, 8); // X1 = list.head
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X29, 24, 8); // save current

    var loopLabel = $"__{funcName}_loop_{_uniqueLabelCounter}";
    var loopDoneLabel = $"__{funcName}_done_{_uniqueLabelCounter}";
    _uniqueLabelCounter++;

    DefineLabel(loopLabel);
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 24, 8); // X0 = current
    _condBranchFixups.Add((_code.Count, loopDoneLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X0)); // CBZ X0, done

    // Save next before modifying
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X1, ARM64Register.X0, 0, 8); // X1 = current.next
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X29, 32, 8); // save next

    // Zero node links
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X0, 0, 8); // next = 0
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X0, 8, 8); // prev = 0
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X0, 16, 8); // list = 0

    if (managed) {
      // Decref the heap value at [node+24]
      EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 24, 8); // X0 = current
      EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X0, 24, 8); // X0 = node.value
      if (Compiler.MmTrace) EmitAdrpAddFixup(ARM64Register.X1, _symdataAdrpFixups, "__mm_scope_list_clear");
      else EmitMovRegImm(ARM64Register.X1, 0);
      EmitBranchLink("mm_decref");
    }

    // Decref/free the node itself
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 24, 8); // X0 = current
    if (Compiler.MmTrace) EmitAdrpAddFixup(ARM64Register.X1, _symdataAdrpFixups, "__mm_scope_list_clear");
    else EmitMovRegImm(ARM64Register.X1, 0);
    EmitBranchLink("mm_decref");

    // current = next
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 32, 8);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X29, 24, 8);
    EmitBranch(loopLabel);

    DefineLabel(loopDoneLabel);

    // Zero list metadata
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X0, 0, 8); // head = 0
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X0, 8, 8); // tail = 0
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.Xzr, ARM64Register.X0, 16, 8); // count = 0

    EmitRuntimeFunctionEnd();
  }

  // --- maxon_managed_list_decref_values(list_ptr) ---
  private void EmitManagedListDecrefValues() {
    // Args: X0=list_ptr [x29,#16]
    // Extra stack: [x29,#24]=current, [x29,#32]=next
    EmitRuntimeFunctionStart("maxon_managed_list_decref_values", 1, 0x50);

    // current = list.head
    EmitReloadArg(0); // X0 = list_ptr
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X1, ARM64Register.X0, 0, 8);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X29, 24, 8);

    var loopLabel = $"__mldv_loop_{_uniqueLabelCounter}";
    var doneLabel = $"__mldv_done_{_uniqueLabelCounter}";
    _uniqueLabelCounter++;

    DefineLabel(loopLabel);
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 24, 8); // X0 = current
    _condBranchFixups.Add((_code.Count, doneLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X0)); // CBZ X0, done

    // Save next
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X1, ARM64Register.X0, 0, 8); // X1 = current.next
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X1, ARM64Register.X29, 32, 8);

    // Decref value at [node+24]
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X0, 24, 8); // X0 = node.value
    EmitMovRegImm(ARM64Register.X1, 0); // scope=NULL
    EmitBranchLink("mm_decref");

    // current = next
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 32, 8);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X29, 24, 8);
    EmitBranch(loopLabel);

    DefineLabel(doneLabel);
    EmitRuntimeFunctionEnd();
  }

  /// <summary>
  /// mm_trace_print_tag(cstr_ptr_x0): Print a null-terminated string to stderr.
  /// </summary>
  private void EmitMmTracePrintTag() {
    EmitRuntimeFunctionStart("mm_trace_print_tag", 1, 0x30);
    EmitReloadArg(0); // X0 = cstr_ptr
    EmitBranchLink("rt_write_cstr_stderr");
    EmitRuntimeFunctionEnd();
  }

  /// <summary>
  /// mm_trace_print_i64(value_x0): Print a 64-bit integer in decimal to stderr.
  /// Uses a 24-byte buffer on the stack.
  /// </summary>
  private void EmitMmTracePrintI64() {
    EmitRuntimeFunctionStart("mm_trace_print_i64", 1, 0x40);
    // [x29+16] = value (arg 0)
    // We'll build the decimal string right-to-left in a stack buffer [x29+24..x29+47] (24 bytes)

    EmitReloadArg(0); // X0 = value

    // If value == 0, print "0"
    EmitCbnz(ARM64Register.X0, "mm_trace_i64_nonzero");
    // Store "0\0" at [x29+24]
    EmitMovRegImm(ARM64Register.X1, 0x30); // '0'
    EmitLoadStoreUnsignedImm(0x39000000, ARM64Register.X1, ARM64Register.X29, 24, 1); // STRB
    EmitMovRegImm(ARM64Register.X1, 0);
    EmitLoadStoreUnsignedImm(0x39000000, ARM64Register.X1, ARM64Register.X29, 25, 1); // STRB null
    EmitAddSubImm(ARM64Register.X0, ARM64Register.X29, 24, isAdd: true);
    EmitBranchLink("rt_write_cstr_stderr");
    EmitBranch("mm_trace_i64_done");

    DefineLabel("mm_trace_i64_nonzero");
    // X0 = value, X9 = pointer to end of buffer (null terminator position)
    EmitAddSubImm(ARM64Register.X9, ARM64Register.X29, 47, isAdd: true); // end of 24-byte buf
    // Null-terminate
    EmitMovRegImm(ARM64Register.X1, 0);
    EmitLoadStoreUnsignedImm(0x39000000, ARM64Register.X1, ARM64Register.X9, 0, 1);

    EmitMovRegImm(ARM64Register.X2, 10); // divisor

    DefineLabel("mm_trace_i64_loop");
    // UDIV X3, X0, X2 (quotient)
    EmitWord(0x9AC20803); // UDIV X3, X0, X2
    // MSUB X4, X3, X2, X0 → X4 = X0 - X3*X2 (remainder)
    EmitWord(0x9B028064); // MSUB X4, X3, X2, X0
    // Convert to ASCII: X4 = X4 + '0'
    EmitAddSubImm(ARM64Register.X4, ARM64Register.X4, 0x30, isAdd: true);
    // Decrement pointer
    EmitAddSubImm(ARM64Register.X9, ARM64Register.X9, 1, isAdd: false);
    // Store digit: STRB W4, [X9]
    EmitLoadStoreUnsignedImm(0x39000000, ARM64Register.X4, ARM64Register.X9, 0, 1);
    // quotient → value
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X3);
    // Loop if value != 0
    EmitCbnz(ARM64Register.X0, "mm_trace_i64_loop");

    // Print: X0 = pointer to first digit (X9)
    EmitMovRegReg(ARM64Register.X0, ARM64Register.X9);
    EmitBranchLink("rt_write_cstr_stderr");

    DefineLabel("mm_trace_i64_done");
    EmitRuntimeFunctionEnd();
  }

  /// <summary>
  /// mm_trace_print_hex(value_x0): Print a 64-bit value as "0xHEX" to stderr.
  /// Uses a 24-byte buffer on the stack for "0x" + 16 hex digits + null.
  /// </summary>
  private void EmitMmTracePrintHex() {
    DefineSymdata("__mm_hex_chars", "0123456789abcdef\0"u8.ToArray());

    EmitRuntimeFunctionStart("mm_trace_print_hex", 1, 0x50);
    // [x29+16] = value (arg 0)
    // Buffer at [x29+24..x29+42] = 19 bytes ("0x" + 16 hex + null)

    EmitReloadArg(0); // X0 = value
    // Save value at [x29+48] (scratch)
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X29, 48, 8);

    // Write '0' at buf[0], 'x' at buf[1]
    EmitMovRegImm(ARM64Register.X1, 0x30); // '0'
    EmitLoadStoreUnsignedImm(0x39000000, ARM64Register.X1, ARM64Register.X29, 24, 1); // STRB
    EmitMovRegImm(ARM64Register.X1, 0x78); // 'x'
    EmitLoadStoreUnsignedImm(0x39000000, ARM64Register.X1, ARM64Register.X29, 25, 1); // STRB

    // Load hex chars table address
    EmitAdrpAddFixup(ARM64Register.X2, _symdataAdrpFixups, "__mm_hex_chars");

    // X0 = value, X3 = digit index (15 down to 0)
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 48, 8);
    EmitMovRegImm(ARM64Register.X3, 15);

    DefineLabel("mm_trace_hex_loop");
    // Extract low nybble: X4 = X0 & 0xF
    EmitWord(0x92400C04); // AND X4, X0, #0xF
    // Look up hex char: X4 = [X2 + X4] (byte load)
    // LDRB W4, [X2, X4]
    EmitWord(0x38646844);
    // Store at buf[2 + X3]: address = x29 + 26 + X3
    EmitAddSubImm(ARM64Register.X5, ARM64Register.X29, 26, isAdd: true);
    // ADD X5, X5, X3
    EmitWord(0x8B0300A5);
    // STRB W4, [X5]
    EmitLoadStoreUnsignedImm(0x39000000, ARM64Register.X4, ARM64Register.X5, 0, 1);
    // Shift value right by 4: LSR X0, X0, #4
    EmitWord(0xD344FC00);
    // Decrement counter: SUBS X3, X3, #1 (sets flags)
    EmitWord(0xF1000463); // SUBS X3, X3, #1
    // Loop while X3 >= 0 (B.GE)
    EmitBranchCond(ARM64ConditionCode.Ge, "mm_trace_hex_loop");

    // Null-terminate at buf[18]
    EmitMovRegImm(ARM64Register.X1, 0);
    EmitLoadStoreUnsignedImm(0x39000000, ARM64Register.X1, ARM64Register.X29, 42, 1); // STRB

    // Print buffer
    EmitAddSubImm(ARM64Register.X0, ARM64Register.X29, 24, isAdd: true);
    EmitBranchLink("rt_write_cstr_stderr");

    EmitRuntimeFunctionEnd();
  }

  // =========================================================================
  // Trace runtime functions
  // =========================================================================

  /// <summary>
  /// mm_trace_print_packed_tag(user_ptr in X0): Extract tag_index from [ptr-24],
  /// look up tag string, and print it.
  /// </summary>
  private void EmitMmTracePrintPackedTag() {
    EmitRuntimeFunctionStart("mm_trace_print_packed_tag", 1, 0x30);
    // [x29+16] = user_ptr
    EmitReloadArg(0); // X0 = user_ptr
    // LDUR X0, [X0, #-24] -- load packed value
    EmitWord(0xF85E8000 | (Reg(ARM64Register.X0) << 5) | Reg(ARM64Register.X0));
    // AND X0, X0, #0xFFFF -- extract tag_index
    EmitMovRegImm(ARM64Register.X1, 0xFFFF);
    // AND X0, X0, X1
    EmitWord(0x8A010000 | (Reg(ARM64Register.X1) << 16) | (Reg(ARM64Register.X0) << 5) | Reg(ARM64Register.X0));
    // Call mm_tag_lookup(tag_index) -> X0 = cstr
    EmitBranchLink("mm_tag_lookup");
    // Call mm_trace_print_tag(cstr)
    EmitBranchLink("mm_trace_print_tag");
    EmitRuntimeFunctionEnd();
  }

  /// <summary>
  /// mm_trace_print_indent(): Print 2 spaces for each level of __mm_trace_depth.
  /// </summary>
  private void EmitMmTracePrintIndent() {
    EmitRuntimeFunctionStart("mm_trace_print_indent", 0, 0x30);
    // Load __mm_trace_depth into X0
    EmitGlobalLoadReg(ARM64Register.X0, "__mm_trace_depth");
    // Store as loop counter at [x29+16]
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X29, 16, 8);

    DefineLabel("mm_trace_indent_loop");
    // Load counter
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 16, 8);
    // If zero, done
    var doneLabel = "mm_trace_indent_done";
    _condBranchFixups.Add((_code.Count, doneLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X0)); // CBZ X0, done
    // Print "  "
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_indent");
    EmitBranchLink("mm_trace_print_tag");
    // Decrement counter
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, 16, 8);
    EmitAddSubImm(ARM64Register.X0, ARM64Register.X0, 1, isAdd: false);
    EmitLoadStoreUnsignedImm(0xF9000000, ARM64Register.X0, ARM64Register.X29, 16, 8);
    EmitBranch("mm_trace_indent_loop");

    DefineLabel(doneLabel);
    EmitRuntimeFunctionEnd();
  }

  /// <summary>
  /// mm_trace_transfer(ptr in X0, scope in X1): Print transfer trace line.
  /// </summary>
  private void EmitMmTraceTransfer() {
    EmitRuntimeFunctionStart("mm_trace_transfer", 2, 0x30);
    // [x29+16]=ptr, [x29+24]=scope
    EmitReloadArg(0); // X0 = ptr
    // If null, return
    var nullLabel = "mm_trace_transfer_null";
    _condBranchFixups.Add((_code.Count, nullLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X0)); // CBZ X0, null
    // Print indent
    EmitBranchLink("mm_trace_print_indent");
    // Print "transfer "
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_transfer");
    EmitBranchLink("mm_trace_print_tag");
    // Print TagAndId
    EmitTraceTagAndId(16);
    // Print Rc
    EmitTraceRc(16);
    // Print ScopeAndNewline
    EmitMmTraceScopeAndNewline("mm_trace_transfer_no_scope", 24);
    DefineLabel(nullLabel);
    EmitRuntimeFunctionEnd();
  }

  /// <summary>
  /// mm_tag_lookup(tag_index in X0) -> cstr in X0
  /// Loop through tag table entries. Return matching tag string or default.
  /// </summary>
  private void EmitMmTagLookup(List<string?>? tagTable) {
    EmitRuntimeFunctionStart("mm_tag_lookup", 1, 0x30);
    // [x29+16] = tag_index
    if (tagTable != null) {
      for (int i = 1; i < tagTable.Count; i++) {
        var label = tagTable[i];
        if (label == null) continue;
        EmitReloadArg(0); // X0 = tag_index
        EmitMovRegImm(ARM64Register.X1, i);
        // CMP X0, X1
        EmitWord(0xEB00001F | (Reg(ARM64Register.X1) << 16) | (Reg(ARM64Register.X0) << 5));
        var skipLabel = $"mm_tag_lookup_skip_{_uniqueLabelCounter++}";
        _condBranchFixups.Add((_code.Count, skipLabel));
        EmitWord(0x54000000 | CondCode(ARM64ConditionCode.Ne)); // B.NE skip
        // Match: return tag string address (label is a symdata key defined during MLIR lowering)
        EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, label);
        EmitRuntimeFunctionEnd();
        DefineLabel(skipLabel);
      }
    }
    // Default: return "?"
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_null");
    EmitRuntimeFunctionEnd();
  }

  // =========================================================================
  // Inline trace helper methods (emit ARM64 code inline, not standalone functions)
  // =========================================================================

  /// <summary>
  /// Print "TypeName " from packed tag at [x29+ptrSlot], then " #N" where N = alloc_id.
  /// </summary>
  private void EmitTraceTagAndId(int ptrSlot) {
    // Call mm_trace_print_packed_tag(ptr)
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, ptrSlot, 8);
    EmitBranchLink("mm_trace_print_packed_tag");
    // Print " #"
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_hash");
    EmitBranchLink("mm_trace_print_tag");
    // Print alloc_id = [ptr-24] >> 16
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, ptrSlot, 8);
    // LDUR X0, [X0, #-24]
    EmitWord(0xF85E8000 | (Reg(ARM64Register.X0) << 5) | Reg(ARM64Register.X0));
    // LSR X0, X0, #16 = UBFM X0, X0, #16, #63
    EmitWord(0xD350FC00 | (Reg(ARM64Register.X0) << 5) | Reg(ARM64Register.X0));
    EmitBranchLink("mm_trace_print_i64");
  }

  /// <summary>
  /// Print " rc=N" from user_ptr at [x29+ptrSlot]. rcSubtract adjusts displayed value.
  /// </summary>
  private void EmitTraceRc(int ptrSlot, int rcSubtract = 0) {
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_rc_eq");
    EmitBranchLink("mm_trace_print_tag");
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, ptrSlot, 8);
    // LDUR X0, [X0, #-8] (refcount)
    EmitWord(0xF85F8000 | (Reg(ARM64Register.X0) << 5) | Reg(ARM64Register.X0));
    if (rcSubtract > 0) EmitAddSubImm(ARM64Register.X0, ARM64Register.X0, rcSubtract, isAdd: false);
    EmitBranchLink("mm_trace_print_i64");
  }

  /// <summary>
  /// Print " size=N" from size value at [x29+sizeSlot].
  /// </summary>
  private void EmitTraceSize(int sizeSlot) {
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_size_eq");
    EmitBranchLink("mm_trace_print_tag");
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, sizeSlot, 8);
    EmitBranchLink("mm_trace_print_i64");
  }

  /// <summary>
  /// Print " [scope]" if scope is non-null, then print newline.
  /// </summary>
  private void EmitMmTraceScopeAndNewline(string skipLabel, int scopeSlot) {
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, scopeSlot, 8);
    _condBranchFixups.Add((_code.Count, skipLabel));
    EmitWord(0xB4000000 | Reg(ARM64Register.X0)); // CBZ X0, skip
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_lbracket");
    EmitBranchLink("mm_trace_print_tag");
    EmitLoadStoreUnsignedImm(0xF9400000, ARM64Register.X0, ARM64Register.X29, scopeSlot, 8);
    EmitBranchLink("mm_trace_print_tag");
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_rbracket");
    EmitBranchLink("mm_trace_print_tag");
    DefineLabel(skipLabel);
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, "__mm_tag_newline");
    EmitBranchLink("mm_trace_print_tag");
  }

  /// <summary>
  /// Emit inline trace: indent + tag + "TypeName #N rc=R [scope]\n".
  /// </summary>
  private void EmitInlineTrace(string tagLabel, string uniquePrefix, int ptrSlot, int scopeSlot,
      bool printRc = true, int rcSubtract = 0, int? sizeSlot = null) {
    EmitBranchLink("mm_trace_print_indent");
    EmitAdrpAddFixup(ARM64Register.X0, _symdataAdrpFixups, tagLabel);
    EmitBranchLink("mm_trace_print_tag");
    EmitTraceTagAndId(ptrSlot);
    if (printRc) EmitTraceRc(ptrSlot, rcSubtract);
    if (sizeSlot.HasValue) EmitTraceSize(sizeSlot.Value);
    EmitMmTraceScopeAndNewline($"{uniquePrefix}_no_scope", scopeSlot);
  }

}
